// Auto-generated on 2025-10-23T00:28:09.237Z
// This file is generated by the CMS and should not be edited manually
// Version 2: Enhanced format with embedded SEO data for zero-database loading
// Source: MongoDB Page collection

export const pageData = {
  "metadata": {
    "serviceSchema": {
      "enabled": false,
      "serviceType": "Online Marketing",
      "areaServed": "Nederland"
    },
    "metaTitle": "Cases & Resultaten | Real Accelerate",
    "metaDescription": "Bewezen resultaten van honderden vastgoedprofessionals. Van lokale makelaars tot internationale projecten – onze beste transformaties."
  },
  "content": {
    "nl": {
      "blocks": [
        {
          "id": "hero",
          "type": "Cases-Hero",
          "order": 0,
          "props": {
            "badge": "Cases & Resultaten",
            "title": "Bewezen resultaten van",
            "titleHighlight": "honderden",
            "subtitle": "Van lokale makelaars tot internationale projecten – onze beste transformaties.",
            "ctaPrimary": "Claim gratis strategiesessie",
            "ctaSecondary": "Bekijk top cases",
            "ctaSecondaryHref": "#beste-cases",
            "stats": [
              {
                "icon": "Users",
                "label": "Clients",
                "value": 200,
                "suffix": "+"
              },
              {
                "icon": "LineChart",
                "label": "Omzetgroei",
                "value": 50,
                "suffix": "M+"
              },
              {
                "icon": "Briefcase",
                "label": "Deals",
                "value": 2847
              },
              {
                "icon": "Globe",
                "label": "Landen",
                "value": 4
              }
            ],
            "image": "/media/rudy-thumbs-up-640x480.png",
            "imageAlt": "Rudy met duim omhoog"
          }
        },
        {
          "id": "best_variants",
          "type": "Cases-BestVariants",
          "order": 1,
          "props": {
            "badge": "Onze beste cases",
            "title": "Uitgelichte transformaties",
            "subtitle": "Een selectie van onze meest indrukwekkende resultaten – strak, helder en geloofwaardig.",
            "featuredBadge": "FEATURED CASE",
            "featuredCompany": "De Brabant Makelaar",
            "featuredSubtitle": "Van 2 naar 8 werknemers in 18 maanden",
            "featuredImage": "/media/case-de-brabant-makelaar-640x480.png",
            "featuredImageAlt": "Team De Brabant Makelaar",
            "stats": [
              {
                "icon": "TrendingUp",
                "label": "Maandomzet",
                "from": "€20k",
                "to": "€65k",
                "suffix": "in 18 maanden"
              },
              {
                "icon": "Target",
                "label": "Trajecten",
                "from": "5",
                "to": "12",
                "suffix": "per maand"
              },
              {
                "icon": "Users2",
                "label": "Team",
                "from": "2",
                "to": "8",
                "suffix": "werknemers"
              },
              {
                "icon": "Building2",
                "label": "Locaties",
                "from": "1",
                "to": "4",
                "suffix": "nieuwe vestigingen"
              }
            ],
            "results": [
              {
                "icon": "TrendingUp",
                "text": "Bewezen marketingmachine ingericht"
              },
              {
                "icon": "Users2",
                "text": "5 aankoopmakelaars actief"
              },
              {
                "icon": "CheckCircle2",
                "text": "Agenda's gevuld met kwalitatieve afspraken"
              }
            ],
            "otherCases": [
              {
                "company": "Thoma Post",
                "sector": "Makelaars",
                "icon": "Home",
                "highlight": "31 afspraken in maand 1",
                "bullets": [
                  "Snelste start",
                  "Kwalitatieve leads",
                  "Consistente pijplijn"
                ],
                "image": "/media/thoma_thumb-640x480.png"
              },
              {
                "company": "Dubai Property",
                "sector": "Internationaal",
                "icon": "Globe2",
                "highlight": "$8.5M+ verkocht",
                "bullets": [
                  "Nationwide events",
                  "IQI Global partner",
                  "Snelle doorloop"
                ],
                "image": "/media/dubai_thumb-640x480.jpg"
              }
            ]
          }
        },
        {
          "id": "video_testimonials",
          "type": "Cases-VideoTestimonials",
          "order": 2,
          "props": {
            "badge": "Video testimonials",
            "title": "Hoor het van makelaars zelf",
            "subtitle": "Echte verhalen van professionals die hun business transformeerden met onze marketing machine.",
            "durationBadge": "~60 sec",
            "activeIndicator": "Nu aan het spelen",
            "sidebarHeader": "Andere verhalen",
            "videos": [
              {
                "id": 1,
                "company": "De Brabant Makelaar",
                "name": "Amory",
                "role": "Eigenaar",
                "thumbnail": "/media/videothumb1-640x480.jpg",
                "videoUrl": "/videos/testimonial-brabant.mp4",
                "quote": "Van €20k naar €65k maandomzet in 18 maanden. De marketing machine werkt echt.",
                "highlight": "225% omzetgroei"
              },
              {
                "id": 2,
                "company": "Bink & Partners",
                "name": "Pieter",
                "role": "Makelaar",
                "thumbnail": "/media/videothumb2-640x480.jpg",
                "videoUrl": "/videos/testimonial-bink.mp4",
                "quote": "Ik betaalde €800 per maand aan slechte leads. Nu heb ik een wachtrij van ideale klanten die mij al willen.",
                "highlight": "30+ afspraken per jaar"
              },
              {
                "id": 3,
                "company": "Thoma Post Makelaardij",
                "name": "Thoma",
                "role": "Eigenaar",
                "thumbnail": "/media/videothumb3-640x480.jpg",
                "videoUrl": "/videos/testimonial-thoma.mp4",
                "quote": "31 kwalitatieve afspraken in de eerste maand. Ik had niet verwacht dat het zo snel zou gaan.",
                "highlight": "Snelste resultaten ooit"
              }
            ]
          }
        },
        {
          "id": "masonry",
          "type": "Cases-Masonry",
          "order": 3,
          "props": {
            "kicker": "Succesverhalen",
            "title": "Hoe makelaars 300% meer leads krijgen",
            "subtitle": "Ontdek hoe ambitieuze makelaars hun business transformeren met onze bewezen aanpak"
          }
        },
        {
          "id": "projects_showcase",
          "type": "Cases-ProjectsShowcase",
          "order": 4,
          "props": {
            "badge": "Onze Projecten",
            "title": "Websites die écht converteren",
            "subtitle": "Bekijk enkele van onze recentste projecten voor ambitieuze makelaars. Van concept tot conversie."
          }
        },
        {
          "id": "industry_breakdown",
          "type": "Cases-IndustryBreakdown",
          "order": 5
        },
        {
          "id": "process_showcase",
          "type": "Cases-ProcessShowcase",
          "order": 6,
          "props": {
            "badge": "Onze Methodologie",
            "title": "Drie stappen naar voorspelbare groei",
            "subtitle": "Onze bewezen 3-stappen methodologie heeft al honderden vastgoedprofessionals geholpen hun bedrijf te laten groeien.",
            "steps": [
              {
                "number": "1",
                "title": "Strategische Analyse",
                "subtitle": "Huidige situatie & doelen in kaart",
                "icon": "Target",
                "items": [
                  "Doelgroep & regio's (exclusiviteit per regio)",
                  "Knelpunten die groei remmen"
                ],
                "timeline": "Week 1-2"
              },
              {
                "number": "2",
                "title": "Custom Marketing Systeem",
                "subtitle": "Implementatie op maat",
                "icon": "Hammer",
                "items": [
                  "Huidige website, campagnes en CRM in kaart",
                  "Doelen afgestemd op resultaatgaranties"
                ],
                "timeline": "Week 3-4"
              },
              {
                "number": "3",
                "title": "Resultaten & Optimalisatie",
                "subtitle": "Meetbare groei realiseren",
                "icon": "TrendingUp",
                "items": [
                  "Meetbare resultaten en groei",
                  "Schaalbaarheid voor lange termijn groei"
                ],
                "timeline": "Maand 2+"
              }
            ]
          }
        },
        {
          "id": "start_your_story",
          "type": "Cases-StartYourStory",
          "order": 7,
          "props": {
            "badge": "Start Jouw Verhaal",
            "title": "WORD DE VOLGENDE",
            "titleHighlight": "SUCCES STORY",
            "benefits": [
              "Analyse huidige situatie en groeidoelen",
              "Identificatie knelpunten die jou tegenhouden",
              "Concreet plan om doelstellingen te behalen"
            ],
            "ctaLabel": "Claim je gratis strategiesessie",
            "ctaSubtext": "30 minuten • Gratis • Vrijblijvend",
            "ctaFootnote": "📅 \"Beperkte plaatsen - alleen voor serieuze groeiers\""
          }
        }
      ]
    }
  },
  "slug": "/cases",
  "title": "Cases & Resultaten",
  "status": "published",
  "updatedAt": "2025-10-20T20:33:41.792Z",
  "seo": {
    "organizationSchema": {
      "address": {
        "streetAddress": "Daalwijkdreef 47",
        "postalCode": "1103 AD",
        "addressLocality": "Amsterdam",
        "addressCountry": "NL"
      },
      "geo": {
        "latitude": 52.3676,
        "longitude": 4.9041
      },
      "openingHours": {
        "dayOfWeek": [
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday"
        ],
        "opens": "09:00",
        "closes": "17:00"
      },
      "name": "Real Accelerate",
      "url": "",
      "logo": "",
      "contactEmail": "",
      "contactPhone": "",
      "socialProfiles": [],
      "description": "Online marketing bureau gespecialiseerd in vastgoedmarketing voor makelaars en vastgoedondernemers"
    }
  },
  "_generated": {
    "at": "2025-10-23T00:28:09.237Z",
    "source": "cms",
    "version": 2
  }
} as const
