// Auto-generated on 2025-10-23T00:28:09.231Z
// This file is generated by the CMS and should not be edited manually
// Version 2: Enhanced format with embedded SEO data for zero-database loading
// Source: MongoDB Page collection

export const pageData = {
  "metadata": {
    "serviceSchema": {
      "enabled": false,
      "serviceType": "Online Marketing",
      "areaServed": "Nederland"
    },
    "metaTitle": "Real Accelerate | Online marketing voor vastgoedprofessionals | Door experts, voor experts",
    "metaDescription": "Groei je vastgoedbedrijf met bewezen online marketing strategieën. Van 2 naar 8 werknemers in 18 maanden. Makelaar marketing, leadgeneratie en automatisering door vastgoedexperts."
  },
  "content": {
    "nl": {
      "blocks": [
        {
          "id": "hero_1",
          "type": "Home-HeroSection",
          "order": 0,
          "props": {
            "kicker": "Voor ambitieuze vastgoedprofessionals",
            "title": "Door vastgoedexperts, voor vastgoedexperts",
            "subtitle": "Vanuit onze eigen ervaring helpen wij jouw bedrijf groeien en projecten sneller verkopen met slimme online marketing.",
            "ctaPrimary": {
              "label": "Plan een bakkie ☕",
              "href": "mailto:info@realaccelerate.nl"
            },
          }
        },
        {
          "id": "trust_strip_1",
          "type": "Home-TrustStrip",
          "order": 1,
          "props": {
            "items": [
              "IQI Global partner",
              "Recreatie",
              "Samen 30+ jaar marketing ervaring",
              "Wereldwijd actief",
              "Nieuwbouw",
              "Projecten",
              "Samen 40+ jaar vastgoed ervaring",
              "Makelaar",
              "Zelf actief in de vastgoedmarkt",
              "Wereldwijd netwerk"
            ],
            "ariaLabel": "Vertrouwen en ervaring"
          }
        },
        {
          "id": "problem_1",
          "type": "Home-ProblemSection",
          "order": 2,
          "props": {
            "kicker": "Het probleem dat wij zien",
            "title": "95% van vastgoedondernemers blijft na 10+ jaar nog steeds afhankelijk van externe leads",
            "subtitle": "Dit is wat we bij veel vastgoedprofessionals terugzien. We delen het om inzicht te geven—zodat je kunt bepalen wat voor jou werkt.",
            "oldSituation": {
              "title": "OUDE SITUATIE",
              "items": [
                {
                  "icon": "XCircle",
                  "text": "Niet mee gaan met technologie"
                },
                {
                  "icon": "ThumbsDown",
                  "text": "Niet onderscheidend"
                },
                {
                  "icon": "Activity",
                  "text": "Geen stabiliteit"
                },
                {
                  "icon": "Frown",
                  "text": "Geleefd worden door je agenda"
                }
              ]
            },
            "newSituation": {
              "title": "ONZE METHODE",
              "items": [
                {
                  "icon": "CheckCircle2",
                  "text": "Geautomatiseerde systemen"
                },
                {
                  "icon": "Crown",
                  "text": "Onderscheidende uitstraling en dienstverlening"
                },
                {
                  "icon": "Banknote",
                  "text": "Stabiel inkomen"
                },
                {
                  "icon": "TrendingUp",
                  "text": "Focus op waar je goed in bent"
                }
              ]
            }
          }
        },
        {
          "id": "case_study_1",
          "type": "Home-CaseStudy",
          "order": 3,
          "props": {
            "title": "Case: De Brabant Makelaar",
            "kicker": "CASE STUDY",
            "subtitle": "In 18 maanden van 2 naar 8 werknemers",
            "tone": "light",
            "frameless": true,
            "showBackdropLogo": false,
            "imageSrc": "/images/case-de-brabant-makelaar.webp",
            "imageAlt": "Team De Brabant Makelaar",
            "kpis": [
              {
                "label": "Maandomzet",
                "from": 20000,
                "to": 65000,
                "unit": "eur",
                "sublabel": "in 18 mnd",
                "span": 2
              },
              {
                "label": "Trajecten per maand",
                "from": 5,
                "to": 12
              }
            ],
            "bullets": [
              "Bewezen marketingmachine ingericht",
              "5 aankoopmakelaars actief",
              "Agenda's gevuld met kwalitatieve afspraken"
            ],
            "ctaPrimary": {
              "label": "Bekijk volledige case",
              "href": "/cases"
            },
            "ctaSecondary": {
              "label": "Alle cases",
              "href": "/cases"
            }
          }
        },
        {
          "id": "unique_approach_1",
          "type": "Home-UniqueApproach",
          "order": 4,
          "props": {
            "kicker": "Onze unieke aanpak",
            "title": "Wij zijn geen standaard marketingbureau. Wij zijn vastgoedondernemers én marketingexperts",
            "subtitle": "Complete marketingaanpak, meetbare groei en ruimte om te ondernemen.",
            "metricValue": "99%",
            "metricLabel": "klanttevredenheid",
            "card1Title": "Nieuwste technieken",
            "card1Description": "Altijd voorop met de laatste marketing innovaties en tools.",
            "card2Title": "Marketing van A tot Z",
            "card2Description": "Complete marketingoplossing zonder gedoe of verborgen kosten.",
            "card3Title": "Voorspelbare groei",
            "card3Description": "Consistente resultaten door bewezen systemen en processen.",
            "card4Title": "Onze eigen ervaring",
            "card4Description": "Vanuit eigen vastgoedervaring weten wij wat werkt in de praktijk.",
            "ctaText": "Klinkt als de juiste fit?",
            "ctaButtonLabel": "Claim gratis strategiesessie",
            "ctaButtonHref": "mailto:info@realaccelerate.nl"
          }
        },
        {
          "id": "flow_connector_1",
          "type": "Home-FlowConnector",
          "order": 5
        },
        {
          "id": "marketing_machine_1",
          "type": "Home-MarketingMachine",
          "order": 6,
          "props": {
            "kicker": "WAT WIJ VOOR JE DOEN",
            "title": "Complete marketing machine voor vastgoedprofessionals",
            "subtitle": "Van eerste indruk tot deal: websites, leadgeneratie, vindbaarheid en opvolging in één systeem.",
            "features": [
              {
                "icon": "Globe",
                "name": "Websites",
                "description": "Professionele websites die converteren. SEO, responsive, en lead-capture ingebouwd.",
                "href": "/cases",
                "cta": "Bekijk voorbeelden",
                "imageSrc": "/images/32.EmiroSmolders-Settle-DSC07215--compressed.webp"
              },
              {
                "icon": "Target",
                "name": "Leadgeneratie",
                "description": "Kwalitatieve leads via Meta & Google. Slim targetten voor maximaal resultaat.",
                "href": "/cases",
                "cta": "Zo werkt het",
                "imageSrc": "/images/leadgen.webp"
              },
              {
                "icon": "GaugeCircle",
                "name": "Vindbaarheid",
                "description": "SEO optimalisatie, Google Business en content die je gevonden laat worden.",
                "href": "/cases",
                "cta": "Onze aanpak",
                "imageSrc": "/images/42.EmiroSmolders-Settle-DSC07252--compressed.webp"
              },
              {
                "icon": "Repeat",
                "name": "Heractivatie",
                "description": "Email en SMS flows die slapende leads wakker maken met relevante triggers.",
                "href": "/cases",
                "cta": "Voorbeeldflows",
                "imageSrc": "/images/rudybrief.webp"
              },
              {
                "icon": "PhoneCall",
                "name": "Leads opvolgen",
                "description": "CRM, automatische follow‑ups en appointment setting. Geen lead meer verloren.",
                "href": "/cases",
                "cta": "Zie systeem",
                "imageSrc": "/images/joeptelefoon.webp"
              },
              {
                "icon": "Palette",
                "name": "Branding",
                "description": "Sterke merkidentiteit: logo, huisstijl en contentstrategie die vertrouwen wekt.",
                "href": "/cases",
                "cta": "Bekijk werk",
                "imageSrc": "/images/47.EmiroSmolders-Settle-DSC07264--compressed.webp"
              }
            ]
          }
        },
        {
          "id": "target_groups_1",
          "type": "Home-TargetGroupsOverview",
          "order": 7,
          "props": {
            "kicker": "DOELGROEPEN",
            "title": "Voor wie wij werken",
            "subtitle": "Gespecialiseerde oplossingen voor elke vastgoedprofessional"
          }
        },
        {
          "id": "target_groups_photos_1",
          "type": "Home-TargetGroupsOverviewPhotos",
          "order": 8,
          "props": {
            "title": "Voor wie wij werken",
            "subtitle": "Gespecialiseerde oplossingen voor elke vastgoedprofessional",
            "items": [
              {
                "name": "Makelaars",
                "description": "Duurzame klant‑relaties ipv lead‑jacht",
                "img": "/images/remax.jpg",
                "alt": "Re/max makelaars",
                "href": "/makelaars",
                "key": "makelaars"
              },
              {
                "name": "Projectontwikkelaars",
                "description": "Project marketing & events",
                "img": "/images/recreatie.jpg",
                "alt": "Recreatie projectontwikkeling",
                "href": "/projectontwikkelaars",
                "key": "projectontwikkelaars"
              },
              {
                "name": "Hypotheekadviseurs",
                "description": "Onafhankelijk van offerte‑sites worden",
                "img": "/images/hypotheekvisie.jpg",
                "alt": "Hypotheekvisie kantoor",
                "href": "/hypotheekadviseurs",
                "key": "hypotheek"
              },
              {
                "name": "Buitenland",
                "description": "IQI Global Partnership • Dubai, Spanje, Bali ervaring",
                "img": "/images/secondhomebeurs.jpg",
                "alt": "Second Home Beurs",
                "href": "/makelaars-buitenland",
                "key": "buitenland"
              }
            ]
          }
        },
        {
          "id": "numbers_1",
          "type": "Home-NumbersSection",
          "order": 9,
          "props": {
            "kicker": "WAAR WE TROTS OP ZIJN",
            "title": "Resultaten in cijfers",
            "stats": [
              {
                "value": "30+",
                "label": "jaar marketing ervaring team"
              },
              {
                "value": "40+",
                "label": "jaar vastgoed ervaring team"
              },
              {
                "value": "600k+",
                "label": "ad spend"
              },
              {
                "value": "1375",
                "label": "bakken koffie"
              }
            ]
          }
        },
        {
          "id": "testimonials_1",
          "type": "Home-TestimonialsSection",
          "order": 10,
          "props": {
            "kicker": "MEER SUCCESVERHALEN",
            "title": "Uitgelichte succesverhalen",
            "durationSec": 70,
            "testimonials": [
              {
                "title": "De Brabant Makelaar",
                "imageSrc": "/images/brabantmakelaar_logo.webp",
                "badges": [
                  "8 makelaars actief",
                  "Agenda gevuld"
                ],
                "author": {
                  "name": "Amory",
                  "handle": "De Brabant Makelaar",
                  "avatar": "/images/brabantmakelaar_avatar.webp"
                },
                "text": "De dynamische heren van Real Accelerate zijn erg fijn om mee samen te werken. Proactief en zorgen voor veel resultaten. Aanrader voor iedereen die meer uit online marketing wilt halen!",
                "href": "/cases"
              },
              {
                "title": "Bink & Partners",
                "imageSrc": "/images/binkpartners_logo.webp",
                "badges": [
                  "Leads boven verwachting",
                  "Website complimenten"
                ],
                "author": {
                  "name": "Pieter",
                  "handle": "Bink & Partners",
                  "avatar": "/images/binkpartners_avatar.webp"
                },
                "text": "Real Accelerate is een enthousiaste groep. Mijn nieuwe website levert veel complimenten op. Het vervolgtraject om op de socials leads te genereren is zojuist gestart en loopt prima.",
                "href": "/cases"
              }
            ]
          }
        },
        {
          "id": "faq_1",
          "type": "Home-FAQSection",
          "order": 11,
          "props": {
            "kicker": "VEELGESTELDE VRAGEN",
            "title": "Frequently Asked Questions",
            "subtitle": "Heeft u nog andere vragen? Neem contact op met ons support team of plan een gratis strategiesessie in.",
            "items": [
              {
                "id": "item-1",
                "icon": "Clock",
                "question": "Hoe snel kan ik aan de slag met jullie marketingaanpak?",
                "answer": "Wij zorgen voor een snelle implementatie van uw marketingmachine. Na onze strategiesessie starten we direct met de opzet van uw campagnes. De eerste resultaten ziet u meestal binnen enkele weken, afhankelijk van uw markt en doelgroep."
              },
              {
                "id": "item-2",
                "icon": "CreditCard",
                "question": "Hoe werkt de samenwerking en wat kan ik verwachten?",
                "answer": "Wij werken transparant en resultaatgericht. Onze tarieven stemmen we af op uw specifieke doelen en situatie. We focussen op meetbare groei en houden u altijd op de hoogte van de voortgang. Neem contact op voor een persoonlijk gesprek over de mogelijkheden."
              },
              {
                "id": "item-3",
                "icon": "Home",
                "question": "Voor welke vastgoedprofessionals is jullie aanpak geschikt?",
                "answer": "Onze marketingaanpak werkt voor alle vastgoedprofessionals: aankoopmakelaars, verkoopmakelaars, hypotheekadviseurs en projectontwikkelaars. Of u nu net begint of al jaren ervaring heeft, wij passen onze strategie aan uw specifieke situatie en doelgroep aan."
              },
              {
                "id": "item-4",
                "icon": "Users",
                "question": "Hoe zorgen jullie voor focus op mijn regio?",
                "answer": "Wij werken met een selectieve aanpak per regio om optimale resultaten te behalen. Dit betekent dat we zorgvuldig kijken naar de marktdynamiek in uw gebied en onze strategie daarop afstemmen. Zo kunnen we ons volledig focussen op uw succes in uw werkgebied."
              },
              {
                "id": "item-5",
                "icon": "Target",
                "question": "Hoe zorgen jullie voor kwalitatieve leads en afspraken?",
                "answer": "Wij richten ons op het aantrekken van kwalitatieve prospects die passen bij uw ideale klantprofiel. Door slimme targeting en bewezen strategieën zorgen we voor een constante stroom van geïnteresseerde potentiële klanten. Kwaliteit staat altijd voorop."
              },
              {
                "id": "item-6",
                "icon": "TrendingUp",
                "question": "Wat maakt jullie aanpak uniek in de vastgoedmarkt?",
                "answer": "Wij zijn zelf actief in de vastgoedmarkt en begrijpen de uitdagingen van makelaars. Onze marketingmachine combineert bewezen strategieën met de nieuwste technieken. Als IQI Global Partner hebben we toegang tot internationale expertise en netwerken."
              }
            ]
          }
        },
        {
          "id": "how_it_works_1",
          "type": "Home-HowItWorksSection",
          "order": 12,
          "props": {
            "kicker": "HOE HET WERKT",
            "title": "Van intake naar voorspelbare groei",
            "subtitle": "Drie heldere stappen. Precies wat je van ons kan verwachten.",
            "steps": [
              {
                "id": 1,
                "title": "Strategische Analyse",
                "subtitle": "Huidige situatie & doelen in kaart",
                "icon": "Lightbulb",
                "bullets": [
                  "Doelgroep & regio's",
                  "Huidige website, campagnes en CRM in kaart",
                  "Knelpunten die groei remmen",
                  "Doelen afgestemd op jouw situatie"
                ]
              },
              {
                "id": 2,
                "title": "Custom Marketing Systeem",
                "subtitle": "Jouw ideale klanten bereiken",
                "icon": "ClipboardCheck",
                "bullets": [
                  "Websites/landingspagina's die converteren",
                  "Leadgeneratie via Meta & Google",
                  "Vindbaarheid (SEO + Google Business)",
                  "Heractivatie + opvolging via CRM en flows"
                ]
              },
              {
                "id": 3,
                "title": "Resultaten & Optimalisatie",
                "subtitle": "Meetbare resultaten en groei",
                "icon": "LineChart",
                "bullets": [
                  "Real time tracking",
                  "Continu optimalisatie"
                ]
              }
            ]
          }
        },
        {
          "id": "final_cta_1",
          "type": "Home-FinalCTA",
          "order": 13,
          "props": {
            "title": "Laten we samen jouw bedrijf naar een hoger niveau tillen",
            "subtitle": "Analyse huidige situatie en groeidoelen",
            "ctaLabel": "Neem contact op",
            "ctaHref": "mailto:info@realaccelerate.nl",
            "bullets": [
              "Analyse huidige situatie en groeidoelen",
              "Identificatie knelpunten die jou tegenhouden",
              "Concreet plan om doelstellingen te behalen"
            ]
          }
        }
      ]
    }
  },
  "slug": "/",
  "title": "Homepage",
  "status": "published",
  "updatedAt": "2025-10-21T09:14:01.327Z",
  "seo": {
    "organizationSchema": {
      "address": {
        "streetAddress": "Daalwijkdreef 47",
        "postalCode": "1103 AD",
        "addressLocality": "Amsterdam",
        "addressCountry": "NL"
      },
      "geo": {
        "latitude": 52.3676,
        "longitude": 4.9041
      },
      "openingHours": {
        "dayOfWeek": [
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday"
        ],
        "opens": "09:00",
        "closes": "17:00"
      },
      "name": "Real Accelerate",
      "url": "",
      "logo": "",
      "contactEmail": "info@realaccelerate.nl",
      "contactPhone": "085 060 2989",
      "socialProfiles": [],
      "description": "Online marketing bureau gespecialiseerd in vastgoedmarketing voor makelaars en vastgoedondernemers"
    }
  },
  "_generated": {
    "at": "2025-10-23T00:28:09.231Z",
    "source": "cms",
    "version": 2
  }
} as const
