// Auto-generated on 2025-10-23T00:28:09.239Z
// This file is generated by the CMS and should not be edited manually
// Version 2: Enhanced format with embedded SEO data for zero-database loading
// Source: MongoDB Page collection

export const pageData = {
  "metadata": {
    "serviceSchema": {
      "enabled": false,
      "serviceType": "Online Marketing",
      "areaServed": "Nederland"
    },
    "metaTitle": "Real Accelerate | Hypotheekadviseur marketing | Onafhankelijk van offerte-sites",
    "metaDescription": "Word onafhankelijk van offerte-sites. Bouw een voorspelbare klantenstroom met bewezen campagnes en duurzaamheid als toegevoegde waarde."
  },
  "content": {
    "nl": {
      "blocks": [
        {
          "id": "hypotheek_hero",
          "type": "Hypotheekadviseurs-Hero",
          "order": 0,
          "props": {
            "kicker": "Voor hypotheekadviseurs",
            "title": "Bewezen campagnes voor hypotheekadviseurs",
            "subtitle": "Word onafhankelijk van offerte-sites en bouw een voorspelbare klantenstroom met <strong>bewezen campagnes</strong> en duurzaamheid als toegevoegde waarde.",
            "ctaPrimary": {
              "label": "Plan een gratis strategiegesprek",
              "href": "/contact"
            },
            "ctaSecondary": {
              "label": "Bekijk Edit BV resultaten",
              "href": "#hypotheek-cases"
            },
            "editBVImage": "/images/editbv.jpg",
            "editBVTitle": "Edit BV Partnership",
            "editBVSubtitle": "Zwolle • Duurzaamheid expertise",
            "editBVStats": [
              {
                "icon": "TrendingUp",
                "text": "46 afspraken uit 1.300 contacten"
              },
              {
                "icon": "Users",
                "text": "Duurzaamheid consulten als differentiator"
              },
              {
                "icon": "Award",
                "text": "Bewezen campagne resultaten"
              }
            ],
            "floatingStat": {
              "value": "3.5%",
              "label": "Conversie ratio"
            },
            "quote": "Van offerte-site afhankelijkheid naar voorspelbare groei",
            "usps": [
              {
                "text": "Stop met dure, slechte leads van Independer/Priva"
              },
              {
                "text": "Word gewaardeerd voor je expertise, niet je prijs"
              },
              {
                "text": "Klanten die <strong>jou al willen</strong> in plaats van leads"
              }
            ]
          }
        },
        {
          "id": "hypotheek_trust_strip",
          "type": "Hypotheekadviseurs-TrustStrip",
          "order": 1,
          "props": {
            "trustItems": [
              "Edit BV partnership Zwolle",
              "46 afspraken uit 1.300 contacten",
              "3.5% conversie ratio bewezen",
              "Duurzaamheid expertise",
              "Onafhankelijk van offerte-sites",
              "Geen Independer/Priva meer",
              "Relationele klanten focus",
              "Bewezen hypotheek campagnes"
            ]
          }
        },
        {
          "id": "hypotheek_pain_points",
          "type": "Hypotheekadviseurs-PainPointsSection",
          "order": 2,
          "props": {
            "badge": "Hypotheekadviseur uitdagingen",
            "title": "Herken jij deze frustraties als hypotheekadviseur?",
            "subtitle": "De meeste hypotheekadviseurs blijven gevangen in een cyclus van slechte leads en prijsconcurrentie. Je bent niet alleen.",
            "challenges": [
              {
                "icon": "DollarSign",
                "title": "Afhankelijkheid van offerte-sites",
                "description": "Je betaalt te veel voor gedeelde leads van lage kwaliteit."
              },
              {
                "icon": "Scale",
                "title": "Prijsconcurrentie",
                "description": "Je wordt vergeleken op prijs in plaats van expertise."
              },
              {
                "icon": "TrendingDown",
                "title": "Lage marges",
                "description": "Steeds meer werk, steeds minder winst."
              },
              {
                "icon": "Clock",
                "title": "Tijdsdruk en administratie",
                "description": "Minder tijd voor advies, meer voor papierwerk."
              },
              {
                "icon": "Award",
                "title": "Geen waardering voor je vakmanschap",
                "description": "Terwijl jij juist het verschil maakt in advies en vertrouwen."
              }
            ],
            "ctaIcon": "Handshake",
            "ctaTitle": "Wij hebben de oplossing!",
            "ctaDescription": "Via Edit BV partnership word je onafhankelijk van offerte-sites met duurzaamheid expertise."
          }
        },
        {
          "id": "hypotheek_edit_bv",
          "type": "Hypotheekadviseurs-EditBVPartnershipSection",
          "order": 3,
          "props": {
            "kicker": "Wij hebben de oplossing",
            "title": "De bewezen oplossing voor hypotheekadviseurs",
            "subtitle": "Met het Real Accelerate Partnership word je onafhankelijk van offerte-sites. Je bouwt een eigen klantenstroom op via duurzaamheidsexpertise en marketingfunnels die voor je werken — 24/7.",
            "benefits": [
              {
                "icon": "TrendingUp",
                "text": "Nieuwe business via duurzaamheidsconsulten"
              },
              {
                "icon": "Target",
                "text": "Eigen leads, direct in je agenda"
              },
              {
                "icon": "Award",
                "text": "Betere marges en hogere klantwaardering"
              },
              {
                "icon": "Users",
                "text": "Complete systemen, begeleiding en community"
              }
            ],
            "oldWayTitle": "TRADITIONELE HYPOTHEEK ADVISERING",
            "newWayTitle": "EDIT BV PARTNERSHIP",
            "newWaySubtitle": "Duurzaamheid + hypotheek expertise",
            "bottomInsight": "<strong>Het verschil:</strong> Van pure hypotheekadvisering naar waardevolle duurzaamheidsexpertise"
          }
        },
        {
          "id": "hypotheek_methodology",
          "type": "Hypotheekadviseurs-MethodologySection",
          "order": 4,
          "props": {
            "kicker": "Onze hypotheek methodologie",
            "title": "Zo maken wij jouw praktijk onafhankelijk",
            "subtitle": "In 4 stappen van afhankelijk naar onafhankelijk",
            "steps": [
              {
                "number": "Stap 1",
                "icon": "Target",
                "title": "IDEALE KLANTPROFIEL",
                "description": "We brengen jouw doelgroep en aanbod helder in kaart"
              },
              {
                "number": "Stap 2",
                "icon": "Lightbulb",
                "title": "WAARDEPROPOSITIE",
                "description": "We combineren hypotheekadvies met duurzaamheidsexpertise"
              },
              {
                "number": "Stap 3",
                "icon": "TrendingUp",
                "title": "MARKETING CAMPAGNE",
                "description": "We bouwen funnels die leads voor je werven"
              },
              {
                "number": "Stap 4",
                "icon": "Handshake",
                "title": "CONTINUE SUPPORT",
                "description": "Begeleiding en optimalisatie voor groei"
              }
            ]
          }
        },
        {
          "id": "hypotheek_voor_wie",
          "type": "Hypotheekadviseurs-VoorWieIsDitSection",
          "order": 5,
          "props": {
            "kicker": "Voor wie is dit?",
            "title": "Voor ambitieuze hypotheekadviseurs met groeidoelen",
            "subtitle": "Onze aanpak werkt het best voor adviseurs die klaar zijn voor verandering en onafhankelijkheid.",
            "perfectForTitle": "Perfect voor hypotheekadviseurs die:",
            "perfectForItems": [
              {
                "icon": "Target",
                "title": "Groei ambitie",
                "description": "Verder willen groeien dan alleen hypotheekadvisering"
              },
              {
                "icon": "TrendingUp",
                "title": "Onafhankelijk",
                "description": "Weg willen van offerte-sites en prijsconcurrentie"
              },
              {
                "icon": "Leaf",
                "title": "Innovatie",
                "description": "Duurzaamheid als differentiator willen inzetten"
              }
            ],
            "notForTitle": "Niet geschikt voor:",
            "notForItems": [
              "Adviseurs die tevreden zijn met status quo",
              "Geen tijd hebben voor verandering",
              "Alleen op prijs willen concurreren"
            ]
          }
        },
        {
          "id": "hypotheek_resultaten",
          "type": "Hypotheekadviseurs-BewezenResultatenSection",
          "order": 6,
          "props": {
            "kicker": "Bewezen resultaten",
            "title": "Resultaten uit de praktijk",
            "subtitle": "Edit BV case study: 46 afspraken uit 1.300 contacten"
          }
        },
        {
          "id": "hypotheek_wat_krijg",
          "type": "Hypotheekadviseurs-WatJeKrijgtSection",
          "order": 7,
          "props": {
            "kicker": "Wat je krijgt",
            "title": "Complete ondersteuning voor hypotheekadviseurs",
            "subtitle": "Van strategie tot uitvoering, wij zorgen dat je onafhankelijk wordt",
            "services": [
              {
                "icon": "Award",
                "title": "Edit BV Partnership",
                "description": "Toegang tot duurzaamheidsexpertise",
                "items": [
                  "Duurzaamheidsconsulten",
                  "Expert netwerk",
                  "Certificering"
                ]
              },
              {
                "icon": "Target",
                "title": "Marketing Campagnes",
                "description": "Bewezen funnels en strategieën",
                "items": [
                  "Lead generation",
                  "Email campagnes",
                  "Social media"
                ]
              }
            ]
          }
        },
        {
          "id": "hypotheek_aanpak",
          "type": "Hypotheekadviseurs-BewezenAanpakSection",
          "order": 8,
          "props": {
            "kicker": "Bewezen aanpak",
            "title": "Waarom onze aanpak werkt",
            "subtitle": "Getest en verbeterd met hypotheekadviseurs zoals jij",
            "points": [
              {
                "icon": "Target",
                "title": "Data gedreven",
                "description": "Elke beslissing is gebaseerd op data en tests"
              },
              {
                "icon": "Lightbulb",
                "title": "Bewezen strategieën",
                "description": "We gebruiken alleen wat werkt bij onze klanten"
              }
            ]
          }
        },
        {
          "id": "hypotheek_cta",
          "type": "Hypotheekadviseurs-StrategieSessionCTA",
          "order": 9,
          "props": {
            "title": "Plan je gratis strategiegesprek",
            "subtitle": "Ontdek of onze aanpak bij jou past",
            "benefits": [
              "30 minuten 1-op-1 strategiesessie",
              "Directe inzichten voor jouw situatie",
              "Geen verplichtingen, gewoon waardevol advies",
              "Plan direct een datum in"
            ],
            "ctaLabel": "Kies een datum en tijd",
            "kicker": "Klaar om te beginnen?"
          }
        },
        {
          "id": "hypotheek_faq",
          "type": "Hypotheekadviseurs-FAQSection",
          "order": 10,
          "props": {
            "kicker": "Veelgestelde Vragen",
            "title": "Vragen van hypotheekadviseurs",
            "subtitle": "Heeft u nog andere vragen? Neem contact op",
            "contactLinkText": "support team",
            "contactLinkHref": "/contact",
            "phoneLabel": "Andere vraag?",
            "phoneNumber": "+31850602989",
            "faqs": [
              {
                "icon": "Clock",
                "question": "Hoe snel zie ik resultaat?",
                "answer": "De eerste leads kunnen binnen 2-4 weken binnenkomen. Structurele groei zie je na 3-6 maanden."
              },
              {
                "icon": "DollarSign",
                "question": "Wat kost het?",
                "answer": "We werken op maat. Investering hangt af van je doelen en huidige situatie."
              },
              {
                "icon": "Target",
                "question": "Voor wie is dit geschikt?",
                "answer": "Voor hypotheekadviseurs die willen groeien en onafhankelijk willen worden van offerte-sites."
              }
            ]
          }
        }
      ]
    }
  },
  "slug": "/hypotheekadviseurs",
  "title": "Hypotheekadviseurs",
  "status": "published",
  "updatedAt": "2025-10-17T08:42:56.105Z",
  "seo": {
    "organizationSchema": {
      "address": {
        "streetAddress": "Daalwijkdreef 47",
        "postalCode": "1103 AD",
        "addressLocality": "Amsterdam",
        "addressCountry": "NL"
      },
      "geo": {
        "latitude": 52.3676,
        "longitude": 4.9041
      },
      "openingHours": {
        "dayOfWeek": [
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday"
        ],
        "opens": "09:00",
        "closes": "17:00"
      },
      "name": "Real Accelerate",
      "url": "",
      "logo": "",
      "contactEmail": "",
      "contactPhone": "",
      "socialProfiles": [],
      "description": "Online marketing bureau gespecialiseerd in vastgoedmarketing voor makelaars en vastgoedondernemers"
    }
  },
  "_generated": {
    "at": "2025-10-23T00:28:09.239Z",
    "source": "cms",
    "version": 2
  }
} as const
