// Auto-generated on 2025-10-23T00:28:09.242Z
// This file is generated by the CMS and should not be edited manually
// Version 2: Enhanced format with embedded SEO data for zero-database loading
// Source: MongoDB Page collection

export const pageData = {
  "metadata": {
    "serviceSchema": {
      "enabled": false,
      "serviceType": "Online Marketing",
      "areaServed": "Nederland"
    },
    "metaTitle": "Real Accelerate | Makelaar marketing | Groei je makelaarskantoor",
    "metaDescription": "Groei je makelaarskantoor met bewezen marketing strategieën uit de praktijk. Van drukte naar structurele groei. Door makelaars, voor makelaars."
  },
  "content": {
    "nl": {
      "blocks": [
        {
          "id": "makelaars_hero",
          "type": "Makelaars-Hero",
          "order": 0,
          "props": {
            "kicker": "Voor groeiende makelaarskantoren",
            "title": "Groei slimmer met je makelaarskantoor",
            "subtitle": "Bij Real Accelerate helpen wij makelaarskantoren groeien met bewezen strategieën, efficiëntere processen en praktische ondersteuning. Geen theorie, maar aanpakken wat écht werkt – rechtstreeks uit de praktijk van ons eigen makelaarskantoor SETTL. en de klanten die wij dagelijks begeleiden.",
            "ctaPrimary": {
              "label": "Plan een gratis strategiesessie",
              "href": "/contact"
            },
            "ctaSecondary": {
              "label": "Ontdek onze aanpak",
              "href": "#methodologie"
            },
            "trustIndicators": [
              {
                "text": "30 minuten strategiesessie"
              },
              {
                "text": "Volledig vrijblijvend"
              },
              {
                "text": "Direct bruikbare inzichten"
              }
            ],
            "avatarsTitle": "Sluit je aan bij 200+ succesvolle makelaars",
            "avatars": [
              {
                "src": "/images/brabantmakelaar_avatar.webp",
                "alt": "Amory - De Brabant Makelaar",
                "tilt": "-rotate-1"
              },
              {
                "src": "/images/binkpartners_avatar.webp",
                "alt": "Pieter - Bink & Partners",
                "tilt": "rotate-3"
              },
              {
                "src": "/images/paulthijssen_avatar.webp",
                "alt": "Paul - Paul Thijssen Makelaardij",
                "tilt": "-rotate-2"
              }
            ],
            "floatingStats": [
              {
                "title": "30+ jaar",
                "subtitle": "Gecombineerde ervaring"
              },
              {
                "title": "SETTL.",
                "subtitle": "Eigen makelaarskantoor"
              }
            ],
            "testimonialQuote": "Honderden makelaars geholpen sinds 2021"
          }
        },
        {
          "id": "makelaars_trust_strip",
          "type": "Makelaars-TrustStrip",
          "order": 1,
          "props": {
            "trustItems": [
              "30+ jaar marketing ervaring",
              "Zelf actief als makelaars met SETTL.",
              "€10k → €100k omzet met onze klanten",
              "Bewezen strategieën uit de praktijk",
              "Van 2 naar 8 werknemers in 18 maanden",
              "Geen afhankelijkheid van dure leadplatformen",
              "Transparant en resultaatgericht",
              "Complete ondersteuning van A tot Z"
            ]
          }
        },
        {
          "id": "makelaars_problem",
          "type": "Makelaars-ProblemSection",
          "order": 2,
          "props": {
            "kicker": "De uitdaging",
            "title": "De uitdaging voor makelaarskantoren",
            "subtitle": "Veel makelaarskantoren draaien volle agenda's en hebben een continue stroom telefoontjes, maar groeien toch niet door. We zien het dagelijks bij onze klanten – en we hebben het zelf ook ervaren met SETTL.",
            "oldWayTitle": "HUIDIGE SITUATIE",
            "oldWaySubtitle": "Waar veel kantoren tegenaan lopen",
            "problems": [
              {
                "text": "Tijd en energie gaan verloren aan ad hoc werk",
                "icon": "AlertTriangle"
              },
              {
                "text": "Dure marketingplatformen leveren weinig op",
                "icon": "DollarSign"
              },
              {
                "text": "Processen zijn versnipperd en niet schaalbaar",
                "icon": "TrendingDown"
              },
              {
                "text": "Drukte zonder duurzame groei",
                "icon": "Swords"
              }
            ],
            "newWayTitle": "ONZE AANPAK",
            "newWaySubtitle": "Hoe wij helpen",
            "solutions": [
              {
                "text": "Bewezen strategieën en systemen",
                "icon": "CheckCircle2"
              },
              {
                "text": "Efficiëntere processen en automatisering",
                "icon": "Target"
              },
              {
                "text": "Structureel bouwen aan een schaalbaar kantoor",
                "icon": "Users"
              },
              {
                "text": "Ervaring uit de praktijk met SETTL.",
                "icon": "CheckCircle2"
              }
            ],
            "bottomInsight": "<strong>Wij weten hoe dat voelt –</strong> en vooral: hoe je er vanaf komt"
          }
        },
        {
          "id": "makelaars_methodology",
          "type": "Makelaars-MethodologySection",
          "order": 3,
          "props": {
            "kicker": "Onze werkwijze",
            "title": "Van drukte naar duurzame groei",
            "subtitle": "Met Real Accelerate zetten we makelaarskantoren om van reactief werken naar voorspelbare groei. Dat doen we in 3 stappen:",
            "steps": [
              {
                "title": "INZICHT KRIJGEN",
                "subtitle": "Stap 1",
                "description": "Analyse van je huidige processen, marketing en resultaten.",
                "icon": "Target"
              },
              {
                "title": "SLIMMER WERKEN",
                "subtitle": "Stap 2",
                "description": "Bewezen systemen en automatisering inzetten.",
                "icon": "Target"
              },
              {
                "title": "SAMEN DOORGROEIEN",
                "subtitle": "Stap 3",
                "description": "Structureel bouwen aan een sterker kantoor.",
                "icon": "TrendingUp"
              }
            ]
          }
        },
        {
          "id": "makelaars_bewezen_systeem",
          "type": "Makelaars-BewezenSysteemSection",
          "order": 4,
          "props": {
            "kicker": "Onze ervaring",
            "title": "Ervaring uit de branche – wij staan er zelf middenin",
            "subtitle": "Real Accelerate is geen traditioneel marketingbureau. Wij zijn makelaars. Met <strong>SETTL.</strong> staan we dagelijks in de markt. Alles wat wij doen voor onze klanten, hebben we zelf getest, verbeterd en bewezen.",
            "imageSrc": "/images/emiro_working_at_desk.png",
            "imageAlt": "Emiro aan het werk achter zijn laptop",
            "benefitsTitle": "WAAROM DIT VERSCHIL MAAKT",
            "benefits": [
              {
                "text": "Ervaring uit de praktijk – wij zijn zelf makelaars"
              },
              {
                "text": "Transparant, no-nonsense samenwerken"
              },
              {
                "text": "Bewezen strategieën en systemen"
              },
              {
                "text": "Altijd gericht op duurzame groei"
              },
              {
                "text": "Persoonlijk en menselijk in onze aanpak"
              }
            ],
            "quote": "Daarom begrijpen wij makelaarskantoren beter dan wie dan ook."
          }
        },
        {
          "id": "makelaars_results",
          "type": "Makelaars-ResultsBentoGrid",
          "order": 5,
          "props": {
            "kicker": "Resultaten uit de praktijk",
            "title": "Bewezen resultaten van makelaars",
            "subtitle": "Onze klanten zijn makelaarskantoren die slimmer willen werken en sneller willen groeien. Met onze aanpak zien ze onder andere:",
            "results": [
              {
                "company": "DE BRABANT MAKELAAR",
                "logo": "/images/brabantmakelaar_logo.webp",
                "image": "/images/1.EmiroSmolders-Settle-DSC06894-.webp",
                "mainMetric": "€10k → €100k/maand",
                "description": "Van 2 naar 8 werknemers in 18 maanden tijd.",
                "icon": "DollarSign",
                "featured": true
              },
              {
                "company": "MARCO VAN BARNEVELD",
                "image": "/images/10.EmiroSmolders-Settle-DSC06970-.jpg",
                "mainMetric": "4 nieuwe franchise locaties",
                "description": "Pipeline vol voor meer groei.",
                "icon": "Building2"
              },
              {
                "company": "THOMA POST",
                "image": "/images/teamfoto_einde.png",
                "mainMetric": "31 afspraken eerste maand",
                "description": "Directe resultaten vanaf dag één.",
                "icon": "Target"
              }
            ],
            "bottomInsight": "<strong>Efficiëntere processen,</strong> meer voorspelbare afspraken en omzet",
            "ctaLabel": "Lees ervaringen van makelaars",
            "ctaHref": "/cases"
          }
        },
        {
          "id": "makelaars_guarantees",
          "type": "Makelaars-GuaranteesSection",
          "order": 6,
          "props": {
            "kicker": "Waarom wij",
            "title": "Waarom makelaars kiezen voor Real Accelerate",
            "subtitle": "Wij zijn geen traditioneel marketingbureau – wij begrijpen de vastgoedbranche van binnenuit",
            "cards": [
              {
                "title": "Ervaring uit de praktijk",
                "subtitle": "Wij zijn zelf makelaars",
                "icon": "Target",
                "items": [
                  "<strong>Ervaring uit de praktijk</strong> – wij zijn zelf makelaars",
                  "<strong>Transparant, no-nonsense</strong> samenwerken",
                  "<strong>Bewezen strategieën</strong> en systemen"
                ]
              },
              {
                "title": "Onze focus",
                "subtitle": "Altijd gericht op resultaat",
                "icon": "Users",
                "items": [
                  "<strong>Altijd gericht op duurzame groei</strong>",
                  "<strong>Persoonlijk en menselijk</strong> in onze aanpak"
                ]
              }
            ]
          }
        },
        {
          "id": "makelaars_what_you_get",
          "type": "Makelaars-WhatYouGetSection",
          "order": 7,
          "props": {
            "kicker": "Wat je krijgt",
            "title": "Meer dan een marketingcampagne",
            "subtitle": "Wij helpen makelaarskantoren niet alleen met marketing of zichtbaarheid. Wij bouwen mee aan het hele fundament van je kantoor:",
            "services": [
              "Branding en positionering",
              "Online marketing en campagnes",
              "Procesoptimalisatie en automatisering",
              "Groei- en schaalstrategieën"
            ],
            "bonusTitle": "Ontdek onze oplossingen",
            "bonusDescription": "Wil je meer weten? Neem contact op."
          }
        },
        {
          "id": "makelaars_for_who",
          "type": "Makelaars-ForWhoIsThisSection",
          "order": 8,
          "props": {
            "kicker": "Voor wie is dit?",
            "title": "Voor welke makelaars is dit interessant?",
            "subtitle": "Onze aanpak past bij makelaarskantoren die:",
            "perfectFor": [
              "Klaar zijn met dure en onvoorspelbare leadplatformen",
              "Efficiëntere processen en meer structuur willen",
              "Een sterk merk willen bouwen in hun regio",
              "Toekomstbestendig en schaalbaar willen groeien"
            ],
            "notForTitle": "Niet geschikt voor:",
            "notFor": [
              "Prijsvechters zonder focus op kwaliteit",
              "Adviseurs die tevreden zijn met hun huidige afhankelijkheid",
              "Wie niet openstaat voor innovatie"
            ],
            "bottomInsight": "<strong>Herken je dit?</strong> Neem contact op"
          }
        },
        {
          "id": "makelaars_cta",
          "type": "Makelaars-StrategieSessionCTA",
          "order": 9,
          "props": {
            "title": "Klaar om je makelaarskantoor naar het volgende niveau te brengen?",
            "subtitle": "Of je nu meer structuur zoekt, je marketing wilt verbeteren of simpelweg efficiënt werken – wij helpen je verder.",
            "benefits": [
              "Analyse van jouw situatie en groeidoelen",
              "Identificatie knelpunten",
              "Concreet plan om doelstellingen te behalen",
              "Vrijblijvend kennismakingsgesprek",
              "Direct bruikbare adviezen",
              "Persoonlijke aanpak"
            ],
            "ctaLabel": "Claim je gratis strategiesessie",
            "ctaSubtext": "30 minuten • Volledig vrijblijvend",
            "ctaHref": "/contact"
          }
        },
        {
          "id": "makelaars_faq",
          "type": "Makelaars-FAQSection",
          "order": 10,
          "props": {
            "kicker": "Veelgestelde Vragen",
            "title": "Vragen van makelaars",
            "subtitle": "Heeft u nog andere vragen? Neem contact op met ons",
            "contactLinkText": "support team",
            "contactLinkHref": "/contact",
            "phoneLabel": "Andere vraag?",
            "phoneNumber": "+31850602989",
            "faqs": [
              {
                "question": "Hoe snel zie ik resultaat?",
                "answer": "Afhankelijk van je huidige situatie zien veel kantoren binnen enkele weken verbetering.",
                "icon": "Clock"
              },
              {
                "question": "Werkt dit ook in mijn regio?",
                "answer": "Ja, onze aanpak is flexibel en aanpasbaar per marktgebied.",
                "icon": "Home"
              },
              {
                "question": "Wat kost het?",
                "answer": "We werken met pakketten op maat. Tijdens een intake bespreken we de investering.",
                "icon": "Target"
              },
              {
                "question": "Moet ik alles uit handen geven?",
                "answer": "Nee, je bepaalt zelf of je volledig ontzorgd wilt worden.",
                "icon": "Users"
              },
              {
                "question": "Wat maakt Real Accelerate anders?eee",
                "answer": "Wij zijn makelaars én adviseurs. Wij helpen met bewezen oplossingen uit de praktijk.",
                "icon": "AlertTriangle"
              }
            ]
          }
        }
      ]
    }
  },
  "slug": "/makelaars",
  "title": "Makelaars",
  "status": "published",
  "updatedAt": "2025-10-17T08:42:56.105Z",
  "seo": {
    "organizationSchema": {
      "address": {
        "streetAddress": "Daalwijkdreef 47",
        "postalCode": "1103 AD",
        "addressLocality": "Amsterdam",
        "addressCountry": "NL"
      },
      "geo": {
        "latitude": 52.3676,
        "longitude": 4.9041
      },
      "openingHours": {
        "dayOfWeek": [
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday"
        ],
        "opens": "09:00",
        "closes": "17:00"
      },
      "name": "Real Accelerate",
      "url": "",
      "logo": "",
      "contactEmail": "",
      "contactPhone": "",
      "socialProfiles": [],
      "description": "Online marketing bureau gespecialiseerd in vastgoedmarketing voor makelaars en vastgoedondernemers"
    }
  },
  "_generated": {
    "at": "2025-10-23T00:28:09.242Z",
    "source": "cms",
    "version": 2
  }
} as const
