// Auto-generated on 2025-10-23T00:28:09.248Z
// This file is generated by the CMS and should not be edited manually
// Version 2: Enhanced format with embedded SEO data for zero-database loading
// Source: MongoDB Page collection

export const pageData = {
  "metadata": {
    "serviceSchema": {
      "enabled": false,
      "serviceType": "Online Marketing",
      "areaServed": "Nederland"
    },
    "metaTitle": "Over ons - Real Accelerate",
    "metaDescription": "Leer het team achter Real Accelerate kennen. Van vastgoedondernemers, voor vastgoedondernemers."
  },
  "content": {
    "nl": {
      "blocks": [
        {
          "id": "hero-1",
          "type": "Over-ons-HeroSection",
          "order": 0,
          "props": {
            "badge": "Over ons",
            "title": "Van",
            "highlightedWord": "vastgoedondernemers",
            "subtitle": "voor vastgoedondernemers",
            "description": "Wij zijn Real Accelerate. Een team dat dagelijks actief is in de vastgoedbranche. We kennen de uitdagingen van binnenuit – omdat we ze zelf ervaren hebben. Vanuit die praktijk helpen we anderen vooruit met een aanpak die vernieuwend, praktisch en resultaatgericht is.",
            "image": "/media/teamfoto_einde-640x480.png",
            "imageAlt": "Team Real Accelerate",
            "stats": [
              {
                "icon": "Users",
                "value": "200+ klanten",
                "label": "Europa-breed"
              },
              {
                "icon": "Globe",
                "value": "IQI Global Partner",
                "label": "Internationale slagkracht"
              }
            ]
          }
        },
        {
          "id": "trust-strip-1",
          "type": "Over-ons-TrustStripSection",
          "order": 1,
          "props": {
            "items": [
              "Samen 30+ jaar marketing ervaring",
              "Gevestigd in Nederland",
              "Samen 40+ jaar vastgoed ervaring",
              "Persoonlijke benadering",
              "Transparante werkwijze",
              "Wereldwijd actief",
              "Data-driven beslissingen",
              "Innovatieve oplossingen",
              "Klantgericht team",
              "Bewezen track record"
            ]
          }
        },
        {
          "id": "mission-1",
          "type": "Over-ons-MissionSection",
          "order": 2,
          "props": {
            "badge": "Onze missie",
            "title": "Waarom Real Accelerate bestaat",
            "subtitle": "De vastgoedbranche vernieuwen en ondernemers helpen om sterker, efficiënter en toekomstbestendig te worden",
            "cards": [
              {
                "icon": "Lightbulb",
                "title": "Het probleem",
                "content": "We zagen te vaak dat professionals in de vastgoedbranche <span class=\"font-semibold text-white\">vastliepen in dezelfde patronen:</span> <span class=\"text-[var(--brand-300)] font-medium\">gebrek aan structuur, afhankelijkheid van externe partijen en een moeizame weg naar groei.</span>"
              },
              {
                "icon": "Rocket",
                "title": "Onze oplossing",
                "content": "Met onze eigen ondernemingen ontwikkelden we <span class=\"font-semibold text-[var(--brand-200)]\">strategieën en systemen die dit doorbraken.</span> <span class=\"text-white font-medium\">Het was een logische stap</span> om die kennis en ervaring te bundelen in Real Accelerate."
              },
              {
                "icon": "Star",
                "title": "Onze impact",
                "content": "Ons doel is helder: <span class=\"font-semibold text-white\">de vastgoedbranche vernieuwen</span> en <span class=\"text-[var(--brand-200)] font-medium\">ondernemers helpen om sterker, efficiënter en toekomstbestendig te worden.</span>"
              }
            ],
            "tagline": "Van vastlooppatronen naar duurzame groei. Van afhankelijkheid naar zelfstandigheid. Van overleven naar floreren."
          }
        },
        {
          "id": "timeline-1",
          "type": "Over-ons-TimelineSection",
          "order": 3,
          "props": {
            "title": "Bedrijf Timeline",
            "subtitle": "Onze reis tot nu toe"
          }
        },
        {
          "id": "team-1",
          "type": "Over-ons-TeamSection",
          "order": 4,
          "props": {
            "badge": "Team",
            "title": "Het team achter Real Accelerate",
            "members": [
              {
                "name": "Joep",
                "role": "Founder — CEO",
                "image": "/media/1.EmiroSmolders-Settle-DSC06894--640x480.webp"
              },
              {
                "name": "Partner Naam",
                "role": "Co-Founder — CTO",
                "image": "/media/2.EmiroSmolders-Settle-DSC06899--640x480.webp"
              },
              {
                "name": "Nina",
                "role": "Klant succes baas",
                "image": "/media/3.EmiroSmolders-Settle-DSC06907--640x480.webp"
              },
              {
                "name": "Ravi",
                "role": "Sales tijger",
                "image": "/media/4.EmiroSmolders-Settle-DSC06915--640x480.webp"
              },
              {
                "name": "Milo",
                "role": "Creatieve baas",
                "image": "/media/5.EmiroSmolders-Settle-DSC06927--640x480.webp"
              },
              {
                "name": "Sofie",
                "role": "Data baas",
                "image": "/media/6.EmiroSmolders-Settle-DSC06931--640x480.webp"
              },
              {
                "name": "Alex",
                "role": "Product owner",
                "image": "/media/10.EmiroSmolders-Settle-DSC06970--640x480.jpg"
              },
              {
                "name": "Maya",
                "role": "Design lead",
                "image": "/media/placeholder.jpg"
              }
            ]
          }
        },
        {
          "id": "core-values-1",
          "type": "Over-ons-CoreValuesSection",
          "order": 5,
          "props": {
            "badge": "Onze Fundamenten",
            "title": "Waarden die ons",
            "highlightedWord": "onderscheiden",
            "subtitle": "Wat ons onderscheidt in de vastgoedbranche. Deze waarden zijn levende principes die dagelijks tot uiting komen in onze acties, beslissingen en de manier waarop we met elkaar en onze klanten samenwerken.",
            "values": [
              {
                "id": "value-1",
                "title": "Integriteit",
                "description": "Eerlijkheid en transparantie in alles wat we doen. Onze klanten kunnen erop vertrouwen dat we onze beloftes nakomen.",
                "icon": "Shield",
                "color": "from-blue-500 to-blue-700",
                "bgGradient": "bg-gradient-to-br from-blue-500/20 to-blue-700/20"
              },
              {
                "id": "value-2",
                "title": "Fun",
                "description": "Werken mag leuk zijn, want energie en plezier zorgen voor betere resultaten. We vinden dat werk energie mag geven: plezier en ambitie gaan hand in hand.",
                "icon": "Lightbulb",
                "color": "from-amber-500 to-orange-600",
                "bgGradient": "bg-gradient-to-br from-amber-500/20 to-orange-600/20"
              },
              {
                "id": "value-3",
                "title": "Samenwerking",
                "description": "De beste resultaten ontstaan door echt teamwork. We werken vanuit vertrouwen en gelijkwaardigheid met onze klanten.",
                "icon": "Users",
                "color": "from-green-500 to-emerald-600",
                "bgGradient": "bg-gradient-to-br from-green-500/20 to-emerald-600/20"
              },
              {
                "id": "value-4",
                "title": "Doelgericht",
                "description": "Alles draagt bij aan tastbare vooruitgang. We maken complexe zaken overzichtelijk en helpen vooruitgang boeken zonder onnodige omwegen.",
                "icon": "Heart",
                "color": "from-red-500 to-pink-600",
                "bgGradient": "bg-gradient-to-br from-red-500/20 to-pink-600/20"
              },
              {
                "id": "value-5",
                "title": "Resultaatgericht",
                "description": "We sturen altijd op concrete impact voor onze klanten. Jouw succes is ons succes - we focussen op meetbare resultaten die waarde toevoegen.",
                "icon": "Award",
                "color": "from-purple-500 to-indigo-600",
                "bgGradient": "bg-gradient-to-br from-purple-500/20 to-indigo-600/20"
              },
              {
                "id": "value-6",
                "title": "Ervaring",
                "description": "Wij spreken niet vanaf de zijlijn. Met ons eigen makelaarskantoor SETTL. en onze activiteiten in vastgoedinvesteringen combineren we ervaring met vernieuwing.",
                "icon": "Target",
                "color": "from-teal-500 to-cyan-600",
                "bgGradient": "bg-gradient-to-br from-teal-500/20 to-cyan-600/20"
              }
            ]
          }
        },
        {
          "id": "partnerships-1",
          "type": "Over-ons-PartnershipsSection",
          "order": 6,
          "props": {
            "badge": "Partnerships",
            "title": "Onze Partnerships",
            "partnerships": [
              {
                "title": "IQI Global",
                "description": "Internationale expansie partner. Versterkt onze slagkracht met wereldwijde aanwezigheid en expertise.",
                "image": "/media/iqiglobal.jpg",
                "features": [
                  "Internationale expansie",
                  "40.000+ agents wereldwijd",
                  "Real Accelerate = IQI NL",
                  "Dubai, Spanje, Bali"
                ]
              },
              {
                "title": "SETTL.",
                "description": "Ons eigen makelaarskantoor waar we dagelijks in de praktijk staan. Alles wat we doen voor onze klanten, hebben we zelf getest, verbeterd en bewezen.",
                "image": "/media/editbv-640x480.jpg",
                "features": [
                  "Eigen makelaarskantoor",
                  "Ervaring uit de praktijk",
                  "Bewezen strategieën",
                  "Real-world testing ground"
                ]
              }
            ],
            "quote": "We spreken niet vanaf de zijlijn, maar met ondernemers die zelf midden in de vastgoedwereld staan en jouw doelen begrijpen.",
            "quoteAuthor": "Real Accelerate"
          }
        },
        {
          "id": "culture-1",
          "type": "Over-ons-CultureSection",
          "order": 7,
          "props": {
            "badge": "ONZE PERSOONLIJKHEID",
            "title": "VAN VASTGOEDONDERNEMERS",
            "subtitle": "Hoe wij werken:",
            "comparisonRows": [
              {
                "aspect": "Kennis & Ervaring",
                "aspectIcon": "BookOpen",
                "other": "Theorieën zonder praktijk",
                "realAccelerate": "Ervaring uit de praktijk"
              },
              {
                "aspect": "Aanpak",
                "aspectIcon": "Compass",
                "other": "Standaard oplossingen",
                "realAccelerate": "We combineren ervaring met vernieuwing"
              },
              {
                "aspect": "Kosten",
                "aspectIcon": "Wallet",
                "other": "Bureau op afstand",
                "realAccelerate": "Ondernemers die zelf midden in de vastgoedwereld staan"
              },
              {
                "aspect": "Service",
                "aspectIcon": "Headphones",
                "other": "Alleen advies, geen hands-on",
                "realAccelerate": "We zeggen waar het op staat"
              },
              {
                "aspect": "Garantie",
                "aspectIcon": "ShieldCheck",
                "other": "Formele relaties",
                "realAccelerate": "Plezier en ambitie gaan hand in hand"
              },
              {
                "aspect": "Relatie",
                "aspectIcon": "Handshake",
                "other": "Snelle transacties",
                "realAccelerate": "Duurzame relaties boven snelle deals"
              }
            ],
            "testimonial": {
              "quote": "Bij ons draait het niet alleen om strategieën en processen, maar vooral om mensen. We werken vanuit vertrouwen en gelijkwaardigheid, en we bouwen liever duurzame relaties dan snelle transacties.",
              "author": "Real Accelerate Team",
              "company": "Over onze aanpak"
            }
          }
        },
        {
          "id": "office-1",
          "type": "Over-ons-OfficeSection",
          "order": 8,
          "props": {
            "badge": "Office & Werkwijze",
            "title": "Waarom samenwerken met ons?",
            "subtitle": "🏢 Bezoek ons in Amsterdam",
            "latitude": 52.3239602,
            "longitude": 4.9586448,
            "address": {
              "street": "Daalwijkdreef 47",
              "city": "1103 AD Amsterdam"
            },
            "phone": "085 060 2989",
            "email": "info@realaccelerate.nl",
            "image": "/media/joep-koffie-640x480.png",
            "imageAlt": "Joep"
          }
        },
        {
          "id": "cta-1",
          "type": "Over-ons-CTASection",
          "order": 9,
          "props": {
            "title": "Klaar voor een",
            "highlightedWord": "strategiesessie",
            "subtitle": "Ontdek hoe we jouw bedrijf naar het volgende niveau kunnen brengen. Plan een vrijblijvende strategiesessie en krijg direct inzicht in jouw groeimogelijkheden.",
            "benefits": [
              "Gratis strategiesessie van 45 minuten",
              "Analyse van jouw huidige situatie en doelen",
              "Concrete aanbevelingen voor groei",
              "Geen verplichtingen, volledig vrijblijvend"
            ],
            "ctaLabel": "Plan je strategiesessie",
            "ctaSubtext": "Waarde €1000 • Volledig vrijblijvend • Direct inplannen"
          }
        }
      ]
    }
  },
  "slug": "/over-ons",
  "title": "Over ons",
  "status": "published",
  "updatedAt": "2025-10-23T00:07:19.201Z",
  "seo": {
    "organizationSchema": {
      "address": {
        "streetAddress": "Daalwijkdreef 47",
        "postalCode": "1103 AD",
        "addressLocality": "Amsterdam",
        "addressCountry": "NL"
      },
      "geo": {
        "latitude": 52.3676,
        "longitude": 4.9041
      },
      "openingHours": {
        "dayOfWeek": [
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday"
        ],
        "opens": "09:00",
        "closes": "17:00"
      },
      "name": "Real Accelerate",
      "url": "",
      "logo": "",
      "contactEmail": "",
      "contactPhone": "",
      "socialProfiles": [],
      "description": "Online marketing bureau gespecialiseerd in vastgoedmarketing voor makelaars en vastgoedondernemers"
    }
  },
  "_generated": {
    "at": "2025-10-23T00:28:09.248Z",
    "source": "cms",
    "version": 2
  }
} as const
