// Auto-generated on 2025-10-23T00:28:09.250Z
// This file is generated by the CMS and should not be edited manually
// Version 2: Enhanced format with embedded SEO data for zero-database loading
// Source: MongoDB Page collection

export const pageData = {
  "metadata": {
    "serviceSchema": {
      "enabled": false,
      "serviceType": "Online Marketing",
      "areaServed": "Nederland"
    },
    "metaTitle": "Projectontwikkelaars - Projecten Sneller Verkocht | Real Accelerate",
    "metaDescription": "Als projectontwikkelaar wil je dat je nieuwbouwprojecten efficiënt verkocht worden. Met Real Accelerate brengen we jouw projecten sneller en creatiever onder de aandacht."
  },
  "content": {
    "nl": {
      "blocks": [
        {
          "id": "hero",
          "type": "Projectontwikkelaars-Hero",
          "order": 0,
          "props": {
            "badge": "Voor projectontwikkelaars",
            "title": "Projecten sneller verkocht",
            "titleHighlight": "met een slimme aanpak",
            "subtitle": "Als projectontwikkelaar wil je dat je nieuwbouwprojecten efficiënt en succesvol verkocht worden. Met Real Accelerate brengen we jouw projecten sneller en creatiever onder de aandacht – met <strong>marketing, beleving en opvolging</strong> die geen kans onbenut laat.",
            "bullets": [
              "Snellere verkoop door gerichte campagnes en sterke positionering",
              "Creatieve beleving die projecten <strong>onderscheidend</strong> maakt",
              "Slimme opvolging met automatisering en persoonlijke begeleiding"
            ],
            "ctaPrimary": {
              "label": "Plan een project strategiesessie"
            },
            "ctaSecondary": {
              "label": "Ontdek onze aanpak",
              "href": "#onze-aanpak"
            },
            "showcaseImage": "/images/projectontwikkelaar.webp",
            "showcaseImageAlt": "Dubai-property.nl - Bewezen projectmarketing expertise",
            "showcaseIcon": "Building2",
            "showcaseTitle": "Dubai-property.nl Success",
            "showcaseSubtitle": "Dubai • Event Marketing Expertise",
            "showcaseStats": [
              {
                "icon": "Calendar",
                "text": "15+ evenementen door heel Nederland"
              },
              {
                "icon": "TrendingUp",
                "text": "Nieuwe projecten in weken uitverkocht"
              },
              {
                "icon": "Award",
                "text": "€8.5M+ verkocht via onze events"
              }
            ],
            "floatingStat": {
              "value": "3 weken",
              "label": "Gemiddelde uitverkoop"
            },
            "showcaseNote": "Bewezen aanpak uit de praktijk van vastgoedondernemers"
          }
        },
        {
          "id": "trust_strip",
          "type": "Projectontwikkelaars-TrustStrip",
          "order": 1,
          "props": {
            "trustItems": [
              "Ervaring als vastgoedondernemers en investeerders",
              "Creatieve campagnes die onderscheiden",
              "Slimme opvolging met automatisering en persoonlijke touch",
              "Van lange verkoopcycli naar snelle resultaten",
              "Complete marketing en beleving expertise",
              "Bewezen projectverkoop strategieën",
              "Nederlandse en internationale projectervaring",
              "Transparante rapportage en continue optimalisatie",
              "Grip en voorspelbaarheid in het verkoopproces",
              "Partner die de vastgoedbranche van binnenuit kent"
            ]
          }
        },
        {
          "id": "pain_points",
          "type": "Projectontwikkelaars-PainPointsSection",
          "order": 2,
          "props": {
            "badge": "Projectontwikkelaar uitdagingen",
            "title": "Herken je deze frustraties bij projectverkoop?",
            "subtitle": "Veel projectontwikkelaars lopen tegen dezelfde uitdagingen aan. Herkenbaar? Dan is er een betere manier.",
            "ctaIcon": "Building2",
            "ctaTitle": "Wij hebben de oplossing!",
            "ctaDescription": "Met onze ervaring als vastgoedondernemers combineren we marketing, beleving en slimme opvolging."
          }
        },
        {
          "id": "dubai_success",
          "type": "Projectontwikkelaars-DubaiSuccessStorySection",
          "order": 3,
          "props": {
            "badge": "Waarom wij",
            "title": "Waarom onze aanpak werkt",
            "subtitle": "Bij Real Accelerate combineren we onze ervaring als vastgoedondernemers en vastgoedinvesteerders met slimme marketing, creatieve campagnes en moderne opvolgsystemen."
          }
        },
        {
          "id": "methodology",
          "type": "Projectontwikkelaars-MethodologySection",
          "order": 4,
          "props": {
            "badge": "Onze project methodologie",
            "title": "Zo zorgen wij voor succesvolle projectverkoop",
            "subtitle": "Onze aanpak is geen losse marketingactie, maar een complete verkoopmachine"
          }
        },
        {
          "id": "bewezen_aanpak",
          "type": "Projectontwikkelaars-BewezenAanpakSection",
          "order": 5,
          "props": {
            "badge": "Onze ervaring",
            "title": "Ervaring als vastgoedondernemers en investeerders",
            "subtitle": "Wij zijn geen traditioneel marketingbureau. Als vastgoedondernemers en vastgoedinvesteerders begrijpen we de uitdagingen van binnenuit. Wat we voor onze klanten doen, hebben we zelf getest, verfijnd en bewezen in de praktijk."
          }
        },
        {
          "id": "resultaten",
          "type": "Projectontwikkelaars-ResultatenBentoGrid",
          "order": 6,
          "props": {
            "badge": "Project resultaten bento grid",
            "title": "Resultaten uit de praktijk",
            "subtitle": "Met onze bewezen aanpak zien projectontwikkelaars dat hun projecten sneller verkopen en beter in de markt worden gezet"
          }
        },
        {
          "id": "wat_je_krijgt",
          "type": "Projectontwikkelaars-WatJeKrijgtSection",
          "order": 7,
          "props": {
            "badge": "Jouw complete pakket",
            "title": "Van uitverkocht project naar volgende deal",
            "subtitle": "Alles onder één dak: events, marketing, leads en support om jouw projecten razendsnel te verkopen."
          }
        },
        {
          "id": "voor_wie",
          "type": "Projectontwikkelaars-VoorWieIsDitSection",
          "order": 8,
          "props": {
            "badge": "Voor wie is dit?",
            "title": "Perfect voor projectontwikkelaars die",
            "subtitle": "Onze aanpak werkt het beste voor ambitieuze ontwikkelaars die klaar zijn voor snelle verkoop"
          }
        },
        {
          "id": "cta",
          "type": "Projectontwikkelaars-StrategieSessionCTA",
          "order": 9,
          "props": {
            "title": "Klaar voor een",
            "titleHighlight": "project strategiesessie",
            "subtitle": "Benieuwd hoe jouw volgende project sneller en slimmer verkocht kan worden? Plan een vrijblijvende strategiesessie en krijg direct inzicht in jouw mogelijkheden.",
            "ctaLabel": "Claim je gratis project strategiesessie",
            "ctaSubtext": "Waarde €1000 • Volledig vrijblijvend • Beperkte plaatsen voor serieuze projectontwikkelaars"
          }
        },
        {
          "id": "faq",
          "type": "Projectontwikkelaars-FAQSection",
          "order": 10,
          "props": {
            "kicker": "VEELGESTELDE VRAGEN",
            "title": "Frequently Asked Questions",
            "subtitle": "Heeft u nog andere vragen? Neem contact op met ons",
            "contactLinkText": "support team",
            "contactLinkHref": "/contact",
            "phoneLabel": "Andere vraag?",
            "phoneNumber": "085 060 2989"
          }
        }
      ]
    }
  },
  "slug": "/projectontwikkelaars",
  "title": "Projectontwikkelaars",
  "status": "published",
  "updatedAt": "2025-10-17T08:59:31.583Z",
  "seo": {
    "organizationSchema": {
      "address": {
        "streetAddress": "Daalwijkdreef 47",
        "postalCode": "1103 AD",
        "addressLocality": "Amsterdam",
        "addressCountry": "NL"
      },
      "geo": {
        "latitude": 52.3676,
        "longitude": 4.9041
      },
      "openingHours": {
        "dayOfWeek": [
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday"
        ],
        "opens": "09:00",
        "closes": "17:00"
      },
      "name": "Real Accelerate",
      "url": "",
      "logo": "",
      "contactEmail": "",
      "contactPhone": "",
      "socialProfiles": [],
      "description": "Online marketing bureau gespecialiseerd in vastgoedmarketing voor makelaars en vastgoedondernemers"
    }
  },
  "_generated": {
    "at": "2025-10-23T00:28:09.250Z",
    "source": "cms",
    "version": 2
  }
} as const
