// Auto-generated by scripts/generate-blocks.ts
// DO NOT EDIT MANUALLY - Run 'npm run generate-blocks' to update

// Cases page components
import Cases_BestVariants from '@/components/sections/cases/BestVariants'
import Cases_Hero from '@/components/sections/cases/Hero'
import Cases_IndustryBreakdown from '@/components/sections/cases/IndustryBreakdown'
import Cases_Masonry from '@/components/sections/cases/Masonry'
import Cases_ProcessShowcase from '@/components/sections/cases/ProcessShowcase'
import Cases_ProjectsShowcase from '@/components/sections/cases/ProjectsShowcase'
import Cases_StartYourStory from '@/components/sections/cases/StartYourStory'
import Cases_VideoTestimonials from '@/components/sections/cases/VideoTestimonials'

// Home page components
import Home_CaseStudy from '@/components/sections/home/CaseStudy'
import Home_FAQSection from '@/components/sections/home/FAQSection'
import Home_FinalCTA from '@/components/sections/home/FinalCTA'
import Home_FlowConnector from '@/components/sections/home/FlowConnector'
import Home_HeroSection from '@/components/sections/home/HeroSection'
import Home_HowItWorksSection from '@/components/sections/home/HowItWorksSection'
import Home_MarketingMachine from '@/components/sections/home/MarketingMachine'
import Home_NumbersSection from '@/components/sections/home/NumbersSection'
import Home_ProblemSection from '@/components/sections/home/ProblemSection'
import Home_TargetGroupsOverview from '@/components/sections/home/TargetGroupsOverview'
import Home_TrustStrip from '@/components/sections/home/TrustStrip'
import Home_UniqueApproach from '@/components/sections/home/UniqueApproach'

// Hr-recruitment page components
import HrRecruitment_FAQSection from '@/components/sections/hr-recruitment/FAQSection'
import HrRecruitment_HeroSection from '@/components/sections/hr-recruitment/HeroSection'
import HrRecruitment_MethodologySection from '@/components/sections/hr-recruitment/MethodologySection'
import HrRecruitment_PainPointsSection from '@/components/sections/hr-recruitment/PainPointsSection'
import HrRecruitment_ResultatenBentoGrid from '@/components/sections/hr-recruitment/ResultatenBentoGrid'
import HrRecruitment_StrategieSessionCTA from '@/components/sections/hr-recruitment/StrategieSessionCTA'
import HrRecruitment_TransformationSection from '@/components/sections/hr-recruitment/TransformationSection'
import HrRecruitment_TrustStripSection from '@/components/sections/hr-recruitment/TrustStripSection'
import HrRecruitment_VoorWieIsDitSection from '@/components/sections/hr-recruitment/VoorWieIsDitSection'
import HrRecruitment_WatJeKrijgtSection from '@/components/sections/hr-recruitment/WatJeKrijgtSection'

// Hypotheekadviseurs page components
import Hypotheekadviseurs_BewezenAanpakSection from '@/components/sections/hypotheekadviseurs/BewezenAanpakSection'
import Hypotheekadviseurs_BewezenResultatenSection from '@/components/sections/hypotheekadviseurs/BewezenResultatenSection'
import Hypotheekadviseurs_EditBVPartnershipSection from '@/components/sections/hypotheekadviseurs/EditBVPartnershipSection'
import Hypotheekadviseurs_FAQSection from '@/components/sections/hypotheekadviseurs/FAQSection'
import Hypotheekadviseurs_Hero from '@/components/sections/hypotheekadviseurs/Hero'
import Hypotheekadviseurs_MethodologySection from '@/components/sections/hypotheekadviseurs/MethodologySection'
import Hypotheekadviseurs_PainPointsSection from '@/components/sections/hypotheekadviseurs/PainPointsSection'
import Hypotheekadviseurs_StrategieSessionCTA from '@/components/sections/hypotheekadviseurs/StrategieSessionCTA'
import Hypotheekadviseurs_TrustStrip from '@/components/sections/hypotheekadviseurs/TrustStrip'
import Hypotheekadviseurs_VoorWieIsDitSection from '@/components/sections/hypotheekadviseurs/VoorWieIsDitSection'
import Hypotheekadviseurs_WatJeKrijgtSection from '@/components/sections/hypotheekadviseurs/WatJeKrijgtSection'

// Makelaars page components
import Makelaars_BewezenSysteemSection from '@/components/sections/makelaars/BewezenSysteemSection'
import Makelaars_FAQSection from '@/components/sections/makelaars/FAQSection'
import Makelaars_ForWhoIsThisSection from '@/components/sections/makelaars/ForWhoIsThisSection'
import Makelaars_GuaranteesSection from '@/components/sections/makelaars/GuaranteesSection'
import Makelaars_Hero from '@/components/sections/makelaars/Hero'
import Makelaars_MethodologySection from '@/components/sections/makelaars/MethodologySection'
import Makelaars_ProblemSection from '@/components/sections/makelaars/ProblemSection'
import Makelaars_ResultsBentoGrid from '@/components/sections/makelaars/ResultsBentoGrid'
import Makelaars_StrategieSessionCTA from '@/components/sections/makelaars/StrategieSessionCTA'
import Makelaars_TrustStrip from '@/components/sections/makelaars/TrustStrip'
import Makelaars_WhatYouGetSection from '@/components/sections/makelaars/WhatYouGetSection'

// Makelaars-buitenland page components
import MakelaarsBuitenland_IQIPartnershipSection from '@/components/sections/makelaars-buitenland/IQIPartnershipSection'
import MakelaarsBuitenland_InternationalCasesSection from '@/components/sections/makelaars-buitenland/InternationalCasesSection'
import MakelaarsBuitenland_InternationalFAQSection from '@/components/sections/makelaars-buitenland/InternationalFAQSection'
import MakelaarsBuitenland_InternationalForWhoIsThisSection from '@/components/sections/makelaars-buitenland/InternationalForWhoIsThisSection'
import MakelaarsBuitenland_InternationalGlobeSection from '@/components/sections/makelaars-buitenland/InternationalGlobeSection'
import MakelaarsBuitenland_InternationalMethodologySection from '@/components/sections/makelaars-buitenland/InternationalMethodologySection'
import MakelaarsBuitenland_InternationalPainPointsSection from '@/components/sections/makelaars-buitenland/InternationalPainPointsSection'
import MakelaarsBuitenland_InternationalStrategySessionCTA from '@/components/sections/makelaars-buitenland/InternationalStrategySessionCTA'
import MakelaarsBuitenland_InternationalWhatYouGetSection from '@/components/sections/makelaars-buitenland/InternationalWhatYouGetSection'
import MakelaarsBuitenland_MakelaarsInternationalHero from '@/components/sections/makelaars-buitenland/MakelaarsInternationalHero'
import MakelaarsBuitenland_MakelaarsInternationalTrustStrip from '@/components/sections/makelaars-buitenland/MakelaarsInternationalTrustStrip'

// Over-ons page components
import OverOns_CTASection from '@/components/sections/over-ons/CTASection'
import OverOns_CoreValuesSection from '@/components/sections/over-ons/CoreValuesSection'
import OverOns_CultureSection from '@/components/sections/over-ons/CultureSection'
import OverOns_HeroSection from '@/components/sections/over-ons/HeroSection'
import OverOns_MissionSection from '@/components/sections/over-ons/MissionSection'
import OverOns_OfficeSection from '@/components/sections/over-ons/OfficeSection'
import OverOns_PartnershipsSection from '@/components/sections/over-ons/PartnershipsSection'
import OverOns_TeamSection from '@/components/sections/over-ons/TeamSection'
import OverOns_TimelineSection from '@/components/sections/over-ons/TimelineSection'
import OverOns_TrustStripSection from '@/components/sections/over-ons/TrustStripSection'

// Projectontwikkelaars page components
import Projectontwikkelaars_BewezenAanpakSection from '@/components/sections/projectontwikkelaars/BewezenAanpakSection'
import Projectontwikkelaars_DubaiSuccessStorySection from '@/components/sections/projectontwikkelaars/DubaiSuccessStorySection'
import Projectontwikkelaars_FAQSection from '@/components/sections/projectontwikkelaars/FAQSection'
import Projectontwikkelaars_Hero from '@/components/sections/projectontwikkelaars/Hero'
import Projectontwikkelaars_MethodologySection from '@/components/sections/projectontwikkelaars/MethodologySection'
import Projectontwikkelaars_PainPointsSection from '@/components/sections/projectontwikkelaars/PainPointsSection'
import Projectontwikkelaars_ResultatenBentoGrid from '@/components/sections/projectontwikkelaars/ResultatenBentoGrid'
import Projectontwikkelaars_StrategieSessionCTA from '@/components/sections/projectontwikkelaars/StrategieSessionCTA'
import Projectontwikkelaars_TrustStrip from '@/components/sections/projectontwikkelaars/TrustStrip'
import Projectontwikkelaars_VoorWieIsDitSection from '@/components/sections/projectontwikkelaars/VoorWieIsDitSection'
import Projectontwikkelaars_WatJeKrijgtSection from '@/components/sections/projectontwikkelaars/WatJeKrijgtSection'

// Special components (non-standard locations)
import { TestimonialsSection } from '@/components/blocks/testimonials-with-marquee'
import { TargetGroupsOverviewPhotos } from '@/components/sections/home/TargetGroupsOverview'

// Component registry
const components: Record<string, any> = {
  'Cases-BestVariants': Cases_BestVariants,
  'Cases-Hero': Cases_Hero,
  'Cases-IndustryBreakdown': Cases_IndustryBreakdown,
  'Cases-Masonry': Cases_Masonry,
  'Cases-ProcessShowcase': Cases_ProcessShowcase,
  'Cases-ProjectsShowcase': Cases_ProjectsShowcase,
  'Cases-StartYourStory': Cases_StartYourStory,
  'Cases-VideoTestimonials': Cases_VideoTestimonials,
  'Home-CaseStudy': Home_CaseStudy,
  'Home-FAQSection': Home_FAQSection,
  'Home-FinalCTA': Home_FinalCTA,
  'Home-FlowConnector': Home_FlowConnector,
  'Home-HeroSection': Home_HeroSection,
  'Home-HowItWorksSection': Home_HowItWorksSection,
  'Home-MarketingMachine': Home_MarketingMachine,
  'Home-NumbersSection': Home_NumbersSection,
  'Home-ProblemSection': Home_ProblemSection,
  'Home-TargetGroupsOverview': Home_TargetGroupsOverview,
  'Home-TrustStrip': Home_TrustStrip,
  'Home-UniqueApproach': Home_UniqueApproach,
  'Hr-recruitment-FAQSection': HrRecruitment_FAQSection,
  'Hr-recruitment-HeroSection': HrRecruitment_HeroSection,
  'Hr-recruitment-MethodologySection': HrRecruitment_MethodologySection,
  'Hr-recruitment-PainPointsSection': HrRecruitment_PainPointsSection,
  'Hr-recruitment-ResultatenBentoGrid': HrRecruitment_ResultatenBentoGrid,
  'Hr-recruitment-StrategieSessionCTA': HrRecruitment_StrategieSessionCTA,
  'Hr-recruitment-TransformationSection': HrRecruitment_TransformationSection,
  'Hr-recruitment-TrustStripSection': HrRecruitment_TrustStripSection,
  'Hr-recruitment-VoorWieIsDitSection': HrRecruitment_VoorWieIsDitSection,
  'Hr-recruitment-WatJeKrijgtSection': HrRecruitment_WatJeKrijgtSection,
  'Hypotheekadviseurs-BewezenAanpakSection': Hypotheekadviseurs_BewezenAanpakSection,
  'Hypotheekadviseurs-BewezenResultatenSection': Hypotheekadviseurs_BewezenResultatenSection,
  'Hypotheekadviseurs-EditBVPartnershipSection': Hypotheekadviseurs_EditBVPartnershipSection,
  'Hypotheekadviseurs-FAQSection': Hypotheekadviseurs_FAQSection,
  'Hypotheekadviseurs-Hero': Hypotheekadviseurs_Hero,
  'Hypotheekadviseurs-MethodologySection': Hypotheekadviseurs_MethodologySection,
  'Hypotheekadviseurs-PainPointsSection': Hypotheekadviseurs_PainPointsSection,
  'Hypotheekadviseurs-StrategieSessionCTA': Hypotheekadviseurs_StrategieSessionCTA,
  'Hypotheekadviseurs-TrustStrip': Hypotheekadviseurs_TrustStrip,
  'Hypotheekadviseurs-VoorWieIsDitSection': Hypotheekadviseurs_VoorWieIsDitSection,
  'Hypotheekadviseurs-WatJeKrijgtSection': Hypotheekadviseurs_WatJeKrijgtSection,
  'Makelaars-BewezenSysteemSection': Makelaars_BewezenSysteemSection,
  'Makelaars-FAQSection': Makelaars_FAQSection,
  'Makelaars-ForWhoIsThisSection': Makelaars_ForWhoIsThisSection,
  'Makelaars-GuaranteesSection': Makelaars_GuaranteesSection,
  'Makelaars-Hero': Makelaars_Hero,
  'Makelaars-MethodologySection': Makelaars_MethodologySection,
  'Makelaars-ProblemSection': Makelaars_ProblemSection,
  'Makelaars-ResultsBentoGrid': Makelaars_ResultsBentoGrid,
  'Makelaars-StrategieSessionCTA': Makelaars_StrategieSessionCTA,
  'Makelaars-TrustStrip': Makelaars_TrustStrip,
  'Makelaars-WhatYouGetSection': Makelaars_WhatYouGetSection,
  'Makelaars-buitenland-IQIPartnershipSection': MakelaarsBuitenland_IQIPartnershipSection,
  'Makelaars-buitenland-InternationalCasesSection': MakelaarsBuitenland_InternationalCasesSection,
  'Makelaars-buitenland-InternationalFAQSection': MakelaarsBuitenland_InternationalFAQSection,
  'Makelaars-buitenland-InternationalForWhoIsThisSection': MakelaarsBuitenland_InternationalForWhoIsThisSection,
  'Makelaars-buitenland-InternationalGlobeSection': MakelaarsBuitenland_InternationalGlobeSection,
  'Makelaars-buitenland-InternationalMethodologySection': MakelaarsBuitenland_InternationalMethodologySection,
  'Makelaars-buitenland-InternationalPainPointsSection': MakelaarsBuitenland_InternationalPainPointsSection,
  'Makelaars-buitenland-InternationalStrategySessionCTA': MakelaarsBuitenland_InternationalStrategySessionCTA,
  'Makelaars-buitenland-InternationalWhatYouGetSection': MakelaarsBuitenland_InternationalWhatYouGetSection,
  'Makelaars-buitenland-MakelaarsInternationalHero': MakelaarsBuitenland_MakelaarsInternationalHero,
  'Makelaars-buitenland-MakelaarsInternationalTrustStrip': MakelaarsBuitenland_MakelaarsInternationalTrustStrip,
  'Over-ons-CTASection': OverOns_CTASection,
  'Over-ons-CoreValuesSection': OverOns_CoreValuesSection,
  'Over-ons-CultureSection': OverOns_CultureSection,
  'Over-ons-HeroSection': OverOns_HeroSection,
  'Over-ons-MissionSection': OverOns_MissionSection,
  'Over-ons-OfficeSection': OverOns_OfficeSection,
  'Over-ons-PartnershipsSection': OverOns_PartnershipsSection,
  'Over-ons-TeamSection': OverOns_TeamSection,
  'Over-ons-TimelineSection': OverOns_TimelineSection,
  'Over-ons-TrustStripSection': OverOns_TrustStripSection,
  'Projectontwikkelaars-BewezenAanpakSection': Projectontwikkelaars_BewezenAanpakSection,
  'Projectontwikkelaars-DubaiSuccessStorySection': Projectontwikkelaars_DubaiSuccessStorySection,
  'Projectontwikkelaars-FAQSection': Projectontwikkelaars_FAQSection,
  'Projectontwikkelaars-Hero': Projectontwikkelaars_Hero,
  'Projectontwikkelaars-MethodologySection': Projectontwikkelaars_MethodologySection,
  'Projectontwikkelaars-PainPointsSection': Projectontwikkelaars_PainPointsSection,
  'Projectontwikkelaars-ResultatenBentoGrid': Projectontwikkelaars_ResultatenBentoGrid,
  'Projectontwikkelaars-StrategieSessionCTA': Projectontwikkelaars_StrategieSessionCTA,
  'Projectontwikkelaars-TrustStrip': Projectontwikkelaars_TrustStrip,
  'Projectontwikkelaars-VoorWieIsDitSection': Projectontwikkelaars_VoorWieIsDitSection,
  'Projectontwikkelaars-WatJeKrijgtSection': Projectontwikkelaars_WatJeKrijgtSection,
  'Home-TestimonialsSection': TestimonialsSection,
  'Home-TargetGroupsOverviewPhotos': TargetGroupsOverviewPhotos,
}

interface Block {
  id: string
  type: string
  order: number
  props?: Record<string, any>
}

interface BlockRendererProps {
  blocks: Block[]
}

export default function BlockRenderer({ blocks }: BlockRendererProps) {
  if (!blocks || blocks.length === 0) {
    return null
  }

  const sortedBlocks = [...blocks].sort((a, b) => a.order - b.order)

  return (
    <>
      {sortedBlocks.map((block) => {
        const Component = components[block.type]
        
        if (!Component) {
          return (
            <div key={block.id} className="p-8 bg-red-50 border border-red-200 rounded">
              <p className="text-red-600">Unknown block type: {block.type}</p>
            </div>
          )
        }

        return <Component key={block.id} {...(block.props || {})} />
      })}
    </>
  )
}
