// Auto-generated by scripts/generate-blocks.ts
// DO NOT EDIT MANUALLY - Run 'npm run generate-blocks' to update

export interface BlockDefinition {
  name: string
  category: string
  description: string
  component?: string
  defaultProps?: Record<string, any>
}

export const BLOCK_REGISTRY: Record<string, BlockDefinition> = {
  'Cases-BestVariants': {
    name: 'Cases - Best variants',
    category: 'Cases',
    description: 'Cases - Best variants',
  },
  'Cases-Hero': {
    name: 'Cases - Hero',
    category: 'Cases',
    description: 'Cases - Hero',
  },
  'Cases-IndustryBreakdown': {
    name: 'Cases - Industry breakdown',
    category: 'Cases',
    description: 'Cases - Industry breakdown',
  },
  'Cases-Masonry': {
    name: 'Cases - Masonry',
    category: 'Cases',
    description: 'Cases - Masonry',
  },
  'Cases-ProcessShowcase': {
    name: 'Cases - Process showcase',
    category: 'Cases',
    description: 'Cases - Process showcase',
  },
  'Cases-ProjectsShowcase': {
    name: 'Cases - Projects showcase',
    category: 'Cases',
    description: 'Cases - Projects showcase',
  },
  'Cases-StartYourStory': {
    name: 'Cases - Start your story',
    category: 'Cases',
    description: 'Cases - Start your story',
  },
  'Cases-VideoTestimonials': {
    name: 'Cases - Video testimonials',
    category: 'Cases',
    description: 'Cases - Video testimonials',
  },
  'Home-CaseStudy': {
    name: 'Home - Case study',
    category: 'Home',
    description: 'Home - Case study',
    defaultProps: {
          "title": "Case Study",
          "kicker": "CASE STUDY",
          "subtitle": "Bekijk onze resultaten"
    },
  },
  'Home-FAQSection': {
    name: 'Home - F a q section',
    category: 'Home',
    description: 'Home - F a q section',
    defaultProps: {
          "title": "Veelgestelde vragen",
          "subtitle": "Alles wat je moet weten",
          "items": [
                {
                      "id": "item-1",
                      "icon": "Clock",
                      "question": "Hoe snel kan ik aan de slag met jullie marketingaanpak?",
                      "answer": "Wij zorgen voor een snelle implementatie van uw marketingmachine. Na onze strategiesessie starten we direct met de opzet van uw campagnes. De eerste resultaten ziet u meestal binnen enkele weken, afhankelijk van uw markt en doelgroep."
                },
                {
                      "id": "item-2",
                      "icon": "CreditCard",
                      "question": "Hoe werkt de samenwerking en wat kan ik verwachten?",
                      "answer": "Wij werken transparant en resultaatgericht. Onze tarieven stemmen we af op uw specifieke doelen en situatie. We focussen op meetbare groei en houden u altijd op de hoogte van de voortgang. Neem contact op voor een persoonlijk gesprek over de mogelijkheden."
                },
                {
                      "id": "item-3",
                      "icon": "Home",
                      "question": "Voor welke vastgoedprofessionals is jullie aanpak geschikt?",
                      "answer": "Onze marketingaanpak werkt voor alle vastgoedprofessionals: aankoopmakelaars, verkoopmakelaars, hypotheekadviseurs en projectontwikkelaars. Of u nu net begint of al jaren ervaring heeft, wij passen onze strategie aan uw specifieke situatie en doelgroep aan."
                },
                {
                      "id": "item-4",
                      "icon": "Users",
                      "question": "Hoe zorgen jullie voor focus op mijn regio?",
                      "answer": "Wij werken met een selectieve aanpak per regio om optimale resultaten te behalen. Dit betekent dat we zorgvuldig kijken naar de marktdynamiek in uw gebied en onze strategie daarop afstemmen. Zo kunnen we ons volledig focussen op uw succes in uw werkgebied."
                },
                {
                      "id": "item-5",
                      "icon": "Target",
                      "question": "Hoe zorgen jullie voor kwalitatieve leads en afspraken?",
                      "answer": "Wij richten ons op het aantrekken van kwalitatieve prospects die passen bij uw ideale klantprofiel. Door slimme targeting en bewezen strategieën zorgen we voor een constante stroom van geïnteresseerde potentiële klanten. Kwaliteit staat altijd voorop."
                },
                {
                      "id": "item-6",
                      "icon": "TrendingUp",
                      "question": "Wat maakt jullie aanpak uniek in de vastgoedmarkt?",
                      "answer": "Wij zijn zelf actief in de vastgoedmarkt en begrijpen de uitdagingen van makelaars. Onze marketingmachine combineert bewezen strategieën met de nieuwste technieken. Als IQI Global Partner hebben we toegang tot internationale expertise en netwerken."
                }
          ]
    },
  },
  'Home-FinalCTA': {
    name: 'Home - Final c t a',
    category: 'Home',
    description: 'Home - Final c t a',
    defaultProps: {
          "title": "Klaar om te groeien?",
          "subtitle": "Plan een kennismakingsgesprek",
          "ctaLabel": "Plan een bakkie",
          "ctaHref": "mailto:info@realaccelerate.nl",
          "bullets": [
                "Analyse huidige situatie en groeidoelen",
                "Identificatie knelpunten die jou tegenhouden",
                "Concreet plan om doelstellingen te behalen"
          ]
    },
  },
  'Home-FlowConnector': {
    name: 'Home - Flow connector',
    category: 'Home',
    description: 'Home - Flow connector',
  },
  'Home-HeroSection': {
    name: 'Home - Hero section',
    category: 'Home',
    description: 'Home - Hero section',
    defaultProps: {
          "kicker": "Voor ambitieuze vastgoedprofessionals",
          "title": "Door vastgoedexperts, voor vastgoedexperts",
          "subtitle": "Vanuit onze eigen ervaring helpen wij jouw bedrijf groeien en projecten sneller verkopen met slimme online marketing.",
          "ctaPrimary": {
                "label": "Plan een bakkie ☕",
                "href": "mailto:info@realaccelerate.nl"
          },
          "ctaSecondary": {
                "label": "Bekijk cases",
                "href": "/cases"
          }
    },
  },
  'Home-HowItWorksSection': {
    name: 'Home - How it works section',
    category: 'Home',
    description: 'Home - How it works section',
    defaultProps: {
          "title": "Hoe werkt het?",
          "subtitle": "Van kennismaking tot resultaat in 4 stappen",
          "steps": [
                {
                      "id": 1,
                      "title": "Strategische Analyse",
                      "subtitle": "Huidige situatie & doelen in kaart",
                      "icon": "Lightbulb",
                      "bullets": [
                            "Doelgroep & regio's",
                            "Huidige website, campagnes en CRM in kaart",
                            "Knelpunten die groei remmen",
                            "Doelen afgestemd op jouw situatie"
                      ]
                },
                {
                      "id": 2,
                      "title": "Custom Marketing Systeem",
                      "subtitle": "Jouw ideale klanten bereiken",
                      "icon": "ClipboardCheck",
                      "bullets": [
                            "Websites/landingspagina's die converteren",
                            "Leadgeneratie via Meta & Google",
                            "Vindbaarheid (SEO + Google Business)",
                            "Heractivatie + opvolging via CRM en flows"
                      ]
                },
                {
                      "id": 3,
                      "title": "Resultaten & Optimalisatie",
                      "subtitle": "Meetbare resultaten en groei",
                      "icon": "LineChart",
                      "bullets": [
                            "Real time tracking",
                            "Continu optimalisatie"
                      ]
                }
          ]
    },
  },
  'Home-MarketingMachine': {
    name: 'Home - Marketing machine',
    category: 'Home',
    description: 'Home - Marketing machine',
    defaultProps: {
          "title": "Complete marketing machine voor vastgoedprofessionals",
          "subtitle": "Van eerste indruk tot deal: alles in één systeem.",
          "features": [
                {
                      "icon": "Globe",
                      "name": "Websites",
                      "description": "Professionele websites die converteren. SEO, responsive, en lead-capture ingebouwd.",
                      "href": "/cases",
                      "cta": "Bekijk voorbeelden",
                      "imageSrc": "/images/32.EmiroSmolders-Settle-DSC07215--compressed.webp"
                },
                {
                      "icon": "Target",
                      "name": "Leadgeneratie",
                      "description": "Kwalitatieve leads via Meta & Google. Slim targetten voor maximaal resultaat.",
                      "href": "/cases",
                      "cta": "Zo werkt het",
                      "imageSrc": "/images/leadgen.webp"
                },
                {
                      "icon": "GaugeCircle",
                      "name": "Vindbaarheid",
                      "description": "SEO optimalisatie, Google Business en content die je gevonden laat worden.",
                      "href": "/cases",
                      "cta": "Onze aanpak",
                      "imageSrc": "/images/42.EmiroSmolders-Settle-DSC07252--compressed.webp"
                },
                {
                      "icon": "Repeat",
                      "name": "Heractivatie",
                      "description": "Email en SMS flows die slapende leads wakker maken met relevante triggers.",
                      "href": "/cases",
                      "cta": "Voorbeeldflows",
                      "imageSrc": "/images/rudybrief.webp"
                },
                {
                      "icon": "PhoneCall",
                      "name": "Leads opvolgen",
                      "description": "CRM, automatische follow‑ups en appointment setting. Geen lead meer verloren.",
                      "href": "/cases",
                      "cta": "Zie systeem",
                      "imageSrc": "/images/joeptelefoon.webp"
                },
                {
                      "icon": "Palette",
                      "name": "Branding",
                      "description": "Sterke merkidentiteit: logo, huisstijl en contentstrategie die vertrouwen wekt.",
                      "href": "/cases",
                      "cta": "Bekijk werk",
                      "imageSrc": "/images/47.EmiroSmolders-Settle-DSC07264--compressed.webp"
                }
          ]
    },
  },
  'Home-NumbersSection': {
    name: 'Home - Numbers section',
    category: 'Home',
    description: 'Home - Numbers section',
    defaultProps: {
          "title": "Resultaten in cijfers",
          "stats": [
                {
                      "value": "30+",
                      "label": "jaar marketing ervaring"
                },
                {
                      "value": "40+",
                      "label": "jaar vastgoed ervaring"
                }
          ]
    },
  },
  'Home-ProblemSection': {
    name: 'Home - Problem section',
    category: 'Home',
    description: 'Home - Problem section',
    defaultProps: {
          "kicker": "Het probleem dat wij zien",
          "title": "95% van vastgoedondernemers blijft na 10+ jaar nog steeds afhankelijk van externe leads",
          "subtitle": "Dit is wat we bij veel vastgoedprofessionals terugzien.",
          "oldSituation": {
                "title": "OUDE SITUATIE",
                "items": [
                      {
                            "icon": "XCircle",
                            "text": "Niet mee gaan met technologie"
                      },
                      {
                            "icon": "ThumbsDown",
                            "text": "Niet onderscheidend"
                      },
                      {
                            "icon": "Activity",
                            "text": "Geen stabiliteit"
                      },
                      {
                            "icon": "Frown",
                            "text": "Geleefd worden door je agenda"
                      }
                ]
          },
          "newSituation": {
                "title": "ONZE METHODE",
                "items": [
                      {
                            "icon": "CheckCircle2",
                            "text": "Geautomatiseerde systemen"
                      },
                      {
                            "icon": "Crown",
                            "text": "Onderscheidende uitstraling en dienstverlening"
                      },
                      {
                            "icon": "Banknote",
                            "text": "Stabiel inkomen"
                      },
                      {
                            "icon": "TrendingUp",
                            "text": "Focus op waar je goed in bent"
                      }
                ]
          }
    },
  },
  'Home-TargetGroupsOverview': {
    name: 'Home - Target groups overview',
    category: 'Home',
    description: 'Home - Target groups overview',
    defaultProps: {
          "title": "Voor wie wij werken",
          "subtitle": "Gespecialiseerde oplossingen voor elke vastgoedprofessional"
    },
  },
  'Home-TrustStrip': {
    name: 'Home - Trust strip',
    category: 'Home',
    description: 'Home - Trust strip',
    defaultProps: {
          "items": [
                "IQI Global partner",
                "Recreatie",
                "Samen 30+ jaar marketing ervaring",
                "Wereldwijd actief"
          ],
          "ariaLabel": "Vertrouwen en ervaring"
    },
  },
  'Home-UniqueApproach': {
    name: 'Home - Unique approach',
    category: 'Home',
    description: 'Home - Unique approach',
    defaultProps: {
          "kicker": "Onze unieke aanpak",
          "title": "Wij zijn geen standaard marketingbureau",
          "subtitle": "Complete marketingaanpak, meetbare groei en ruimte om te ondernemen.",
          "metricValue": "99%",
          "metricLabel": "klanttevredenheid",
          "card1Title": "Nieuwste technieken",
          "card1Description": "Altijd voorop met de laatste marketing innovaties en tools.",
          "card2Title": "Marketing van A tot Z",
          "card2Description": "Complete marketingoplossing zonder gedoe of verborgen kosten.",
          "card3Title": "Voorspelbare groei",
          "card3Description": "Consistente resultaten door bewezen systemen en processen.",
          "card4Title": "Onze eigen ervaring",
          "card4Description": "Vanuit eigen vastgoedervaring weten wij wat werkt in de praktijk.",
          "ctaText": "Klinkt als de juiste fit?",
          "ctaButtonLabel": "Claim gratis strategiesessie",
          "ctaButtonHref": "mailto:info@realaccelerate.nl"
    },
  },
  'Hr-recruitment-FAQSection': {
    name: 'Hr-recruitment - F a q section',
    category: 'Hr-recruitment',
    description: 'Hr-recruitment - F a q section',
    defaultProps: {
          "badge": "Veelgestelde Vragen",
          "title": "Vragen van HR-professionals",
          "subtitle": "Heeft u nog andere vragen? Neem contact op met ons support team of plan een gratis strategiesessie in."
    },
  },
  'Hr-recruitment-HeroSection': {
    name: 'Hr-recruitment - Hero section',
    category: 'Hr-recruitment',
    description: 'Hr-recruitment - Hero section',
    defaultProps: {
          "badge": "Voor HR-professionals",
          "titleBefore": "Stop met jagen op",
          "titleHighlight": "kandidaten",
          "subtitle": "Krijg een wachtrij van <strong>gekwalificeerde kandidaten</strong> die bij jouw organisatie passen"
    },
  },
  'Hr-recruitment-MethodologySection': {
    name: 'Hr-recruitment - Methodology section',
    category: 'Hr-recruitment',
    description: 'Hr-recruitment - Methodology section',
    defaultProps: {
          "badge": "Onze bewezen aanpak",
          "title": "Hoe we dit aanpakken",
          "subtitle": "4 stappen naar een recruitment machine"
    },
  },
  'Hr-recruitment-PainPointsSection': {
    name: 'Hr-recruitment - Pain points section',
    category: 'Hr-recruitment',
    description: 'Hr-recruitment - Pain points section',
    defaultProps: {
          "badge": "De 3 grootste frustraties",
          "title": "Herken je dit?",
          "subtitle": "Als HR-professional loop je vast in dezelfde patronen"
    },
  },
  'Hr-recruitment-ResultatenBentoGrid': {
    name: 'Hr-recruitment - Resultaten bento grid',
    category: 'Hr-recruitment',
    description: 'Hr-recruitment - Resultaten bento grid',
    defaultProps: {
          "badge": "Bewezen resultaten",
          "title": "Wat onze klanten bereiken"
    },
  },
  'Hr-recruitment-StrategieSessionCTA': {
    name: 'Hr-recruitment - Strategie session c t a',
    category: 'Hr-recruitment',
    description: 'Hr-recruitment - Strategie session c t a',
    defaultProps: {
          "title": "Klaar voor meer sollicitaties?",
          "subtitle": "Plan een gratis recruitment analyse",
          "ctaLabel": "Plan gratis analyse"
    },
  },
  'Hr-recruitment-TransformationSection': {
    name: 'Hr-recruitment - Transformation section',
    category: 'Hr-recruitment',
    description: 'Hr-recruitment - Transformation section',
    defaultProps: {
          "badge": "Van reactief naar proactief",
          "title": "De transformatie"
    },
  },
  'Hr-recruitment-TrustStripSection': {
    name: 'Hr-recruitment - Trust strip section',
    category: 'Hr-recruitment',
    description: 'Hr-recruitment - Trust strip section',
    defaultProps: {
          "items": [
                "50+ HR-teams geholpen",
                "Recruitment marketing experts",
                "Samen 20+ jaar HR ervaring",
                "Bewezen methodologie",
                "Employer branding specialisten"
          ],
          "ariaLabel": "Vertrouwen en ervaring"
    },
  },
  'Hr-recruitment-VoorWieIsDitSection': {
    name: 'Hr-recruitment - Voor wie is dit section',
    category: 'Hr-recruitment',
    description: 'Hr-recruitment - Voor wie is dit section',
    defaultProps: {
          "badge": "Voor wie is dit?",
          "title": "Is dit de juiste fit voor jou?"
    },
  },
  'Hr-recruitment-WatJeKrijgtSection': {
    name: 'Hr-recruitment - Wat je krijgt section',
    category: 'Hr-recruitment',
    description: 'Hr-recruitment - Wat je krijgt section',
    defaultProps: {
          "badge": "Wat je krijgt",
          "title": "Complete HR recruitment transformatie",
          "subtitle": "Alles wat je nodig hebt om top talent aan te trekken"
    },
  },
  'Hypotheekadviseurs-BewezenAanpakSection': {
    name: 'Hypotheekadviseurs - Bewezen aanpak section',
    category: 'Hypotheekadviseurs',
    description: 'Hypotheekadviseurs - Bewezen aanpak section',
  },
  'Hypotheekadviseurs-BewezenResultatenSection': {
    name: 'Hypotheekadviseurs - Bewezen resultaten section',
    category: 'Hypotheekadviseurs',
    description: 'Hypotheekadviseurs - Bewezen resultaten section',
  },
  'Hypotheekadviseurs-EditBVPartnershipSection': {
    name: 'Hypotheekadviseurs - Edit b v partnership section',
    category: 'Hypotheekadviseurs',
    description: 'Hypotheekadviseurs - Edit b v partnership section',
  },
  'Hypotheekadviseurs-FAQSection': {
    name: 'Hypotheekadviseurs - F a q section',
    category: 'Hypotheekadviseurs',
    description: 'Hypotheekadviseurs - F a q section',
  },
  'Hypotheekadviseurs-Hero': {
    name: 'Hypotheekadviseurs - Hero',
    category: 'Hypotheekadviseurs',
    description: 'Hypotheekadviseurs - Hero',
  },
  'Hypotheekadviseurs-MethodologySection': {
    name: 'Hypotheekadviseurs - Methodology section',
    category: 'Hypotheekadviseurs',
    description: 'Hypotheekadviseurs - Methodology section',
  },
  'Hypotheekadviseurs-PainPointsSection': {
    name: 'Hypotheekadviseurs - Pain points section',
    category: 'Hypotheekadviseurs',
    description: 'Hypotheekadviseurs - Pain points section',
  },
  'Hypotheekadviseurs-StrategieSessionCTA': {
    name: 'Hypotheekadviseurs - Strategie session c t a',
    category: 'Hypotheekadviseurs',
    description: 'Hypotheekadviseurs - Strategie session c t a',
  },
  'Hypotheekadviseurs-TrustStrip': {
    name: 'Hypotheekadviseurs - Trust strip',
    category: 'Hypotheekadviseurs',
    description: 'Hypotheekadviseurs - Trust strip',
  },
  'Hypotheekadviseurs-VoorWieIsDitSection': {
    name: 'Hypotheekadviseurs - Voor wie is dit section',
    category: 'Hypotheekadviseurs',
    description: 'Hypotheekadviseurs - Voor wie is dit section',
  },
  'Hypotheekadviseurs-WatJeKrijgtSection': {
    name: 'Hypotheekadviseurs - Wat je krijgt section',
    category: 'Hypotheekadviseurs',
    description: 'Hypotheekadviseurs - Wat je krijgt section',
  },
  'Makelaars-BewezenSysteemSection': {
    name: 'Makelaars - Bewezen systeem section',
    category: 'Makelaars',
    description: 'Makelaars - Bewezen systeem section',
  },
  'Makelaars-FAQSection': {
    name: 'Makelaars - F a q section',
    category: 'Makelaars',
    description: 'Makelaars - F a q section',
  },
  'Makelaars-ForWhoIsThisSection': {
    name: 'Makelaars - For who is this section',
    category: 'Makelaars',
    description: 'Makelaars - For who is this section',
  },
  'Makelaars-GuaranteesSection': {
    name: 'Makelaars - Guarantees section',
    category: 'Makelaars',
    description: 'Makelaars - Guarantees section',
  },
  'Makelaars-Hero': {
    name: 'Makelaars - Hero',
    category: 'Makelaars',
    description: 'Makelaars - Hero',
  },
  'Makelaars-MethodologySection': {
    name: 'Makelaars - Methodology section',
    category: 'Makelaars',
    description: 'Makelaars - Methodology section',
  },
  'Makelaars-ProblemSection': {
    name: 'Makelaars - Problem section',
    category: 'Makelaars',
    description: 'Makelaars - Problem section',
  },
  'Makelaars-ResultsBentoGrid': {
    name: 'Makelaars - Results bento grid',
    category: 'Makelaars',
    description: 'Makelaars - Results bento grid',
  },
  'Makelaars-StrategieSessionCTA': {
    name: 'Makelaars - Strategie session c t a',
    category: 'Makelaars',
    description: 'Makelaars - Strategie session c t a',
  },
  'Makelaars-TrustStrip': {
    name: 'Makelaars - Trust strip',
    category: 'Makelaars',
    description: 'Makelaars - Trust strip',
  },
  'Makelaars-WhatYouGetSection': {
    name: 'Makelaars - What you get section',
    category: 'Makelaars',
    description: 'Makelaars - What you get section',
  },
  'Makelaars-buitenland-IQIPartnershipSection': {
    name: 'Makelaars-buitenland - I q i partnership section',
    category: 'Makelaars-buitenland',
    description: 'Makelaars-buitenland - I q i partnership section',
  },
  'Makelaars-buitenland-InternationalCasesSection': {
    name: 'Makelaars-buitenland - International cases section',
    category: 'Makelaars-buitenland',
    description: 'Makelaars-buitenland - International cases section',
  },
  'Makelaars-buitenland-InternationalFAQSection': {
    name: 'Makelaars-buitenland - International f a q section',
    category: 'Makelaars-buitenland',
    description: 'Makelaars-buitenland - International f a q section',
  },
  'Makelaars-buitenland-InternationalForWhoIsThisSection': {
    name: 'Makelaars-buitenland - International for who is this section',
    category: 'Makelaars-buitenland',
    description: 'Makelaars-buitenland - International for who is this section',
  },
  'Makelaars-buitenland-InternationalGlobeSection': {
    name: 'Makelaars-buitenland - International globe section',
    category: 'Makelaars-buitenland',
    description: 'Makelaars-buitenland - International globe section',
  },
  'Makelaars-buitenland-InternationalMethodologySection': {
    name: 'Makelaars-buitenland - International methodology section',
    category: 'Makelaars-buitenland',
    description: 'Makelaars-buitenland - International methodology section',
  },
  'Makelaars-buitenland-InternationalPainPointsSection': {
    name: 'Makelaars-buitenland - International pain points section',
    category: 'Makelaars-buitenland',
    description: 'Makelaars-buitenland - International pain points section',
  },
  'Makelaars-buitenland-InternationalStrategySessionCTA': {
    name: 'Makelaars-buitenland - International strategy session c t a',
    category: 'Makelaars-buitenland',
    description: 'Makelaars-buitenland - International strategy session c t a',
  },
  'Makelaars-buitenland-InternationalWhatYouGetSection': {
    name: 'Makelaars-buitenland - International what you get section',
    category: 'Makelaars-buitenland',
    description: 'Makelaars-buitenland - International what you get section',
  },
  'Makelaars-buitenland-MakelaarsInternationalHero': {
    name: 'Makelaars-buitenland - Makelaars international hero',
    category: 'Makelaars-buitenland',
    description: 'Makelaars-buitenland - Makelaars international hero',
  },
  'Makelaars-buitenland-MakelaarsInternationalTrustStrip': {
    name: 'Makelaars-buitenland - Makelaars international trust strip',
    category: 'Makelaars-buitenland',
    description: 'Makelaars-buitenland - Makelaars international trust strip',
  },
  'Over-ons-CTASection': {
    name: 'Over-ons - C t a section',
    category: 'Over-ons',
    description: 'Over-ons - C t a section',
    defaultProps: {
          "title": "Klaar voor een",
          "highlightedWord": "strategiesessie",
          "subtitle": "Ontdek hoe we jouw bedrijf naar het volgende niveau kunnen brengen. Plan een vrijblijvende strategiesessie en krijg direct inzicht in jouw groeimogelijkheden.",
          "benefits": [
                "Gratis strategiesessie van 45 minuten",
                "Analyse van jouw huidige situatie en doelen",
                "Concrete aanbevelingen voor groei",
                "Geen verplichtingen, volledig vrijblijvend"
          ],
          "ctaLabel": "Plan je strategiesessie",
          "ctaSubtext": "Waarde €1000 • Volledig vrijblijvend • Direct inplannen"
    },
  },
  'Over-ons-CoreValuesSection': {
    name: 'Over-ons - Core values section',
    category: 'Over-ons',
    description: 'Over-ons - Core values section',
    defaultProps: {
          "badge": "Onze Fundamenten",
          "title": "Waarden die ons",
          "highlightedWord": "onderscheiden",
          "subtitle": "Wat ons onderscheidt in de vastgoedbranche. Deze waarden zijn levende principes die dagelijks tot uiting komen in onze acties, beslissingen en de manier waarop we met elkaar en onze klanten samenwerken.",
          "values": [
                {
                      "id": "value-1",
                      "title": "Integriteit",
                      "description": "Eerlijkheid en transparantie in alles wat we doen. Onze klanten kunnen erop vertrouwen dat we onze beloftes nakomen.",
                      "icon": "Shield",
                      "color": "from-blue-500 to-blue-700",
                      "bgGradient": "bg-gradient-to-br from-blue-500/20 to-blue-700/20"
                },
                {
                      "id": "value-2",
                      "title": "Fun",
                      "description": "Werken mag leuk zijn, want energie en plezier zorgen voor betere resultaten. We vinden dat werk energie mag geven: plezier en ambitie gaan hand in hand.",
                      "icon": "Lightbulb",
                      "color": "from-amber-500 to-orange-600",
                      "bgGradient": "bg-gradient-to-br from-amber-500/20 to-orange-600/20"
                },
                {
                      "id": "value-3",
                      "title": "Samenwerking",
                      "description": "De beste resultaten ontstaan door echt teamwork. We werken vanuit vertrouwen en gelijkwaardigheid met onze klanten.",
                      "icon": "Users",
                      "color": "from-green-500 to-emerald-600",
                      "bgGradient": "bg-gradient-to-br from-green-500/20 to-emerald-600/20"
                },
                {
                      "id": "value-4",
                      "title": "Doelgericht",
                      "description": "Alles draagt bij aan tastbare vooruitgang. We maken complexe zaken overzichtelijk en helpen vooruitgang boeken zonder onnodige omwegen.",
                      "icon": "Heart",
                      "color": "from-red-500 to-pink-600",
                      "bgGradient": "bg-gradient-to-br from-red-500/20 to-pink-600/20"
                },
                {
                      "id": "value-5",
                      "title": "Resultaatgericht",
                      "description": "We sturen altijd op concrete impact voor onze klanten. Jouw succes is ons succes - we focussen op meetbare resultaten die waarde toevoegen.",
                      "icon": "Award",
                      "color": "from-purple-500 to-indigo-600",
                      "bgGradient": "bg-gradient-to-br from-purple-500/20 to-indigo-600/20"
                },
                {
                      "id": "value-6",
                      "title": "Ervaring",
                      "description": "Wij spreken niet vanaf de zijlijn. Met ons eigen makelaarskantoor SETTL. en onze activiteiten in vastgoedinvesteringen combineren we ervaring met vernieuwing.",
                      "icon": "Target",
                      "color": "from-teal-500 to-cyan-600",
                      "bgGradient": "bg-gradient-to-br from-teal-500/20 to-cyan-600/20"
                }
          ]
    },
  },
  'Over-ons-CultureSection': {
    name: 'Over-ons - Culture section',
    category: 'Over-ons',
    description: 'Over-ons - Culture section',
    defaultProps: {
          "badge": "ONZE PERSOONLIJKHEID",
          "title": "VAN VASTGOEDONDERNEMERS",
          "subtitle": "Hoe wij werken:",
          "comparisonRows": [
                {
                      "aspect": "Kennis & Ervaring",
                      "aspectIcon": "BookOpen",
                      "other": "Theorieën zonder praktijk",
                      "realAccelerate": "Ervaring uit de praktijk"
                },
                {
                      "aspect": "Aanpak",
                      "aspectIcon": "Compass",
                      "other": "Standaard oplossingen",
                      "realAccelerate": "We combineren ervaring met vernieuwing"
                },
                {
                      "aspect": "Kosten",
                      "aspectIcon": "Wallet",
                      "other": "Bureau op afstand",
                      "realAccelerate": "Ondernemers die zelf midden in de vastgoedwereld staan"
                },
                {
                      "aspect": "Service",
                      "aspectIcon": "Headphones",
                      "other": "Alleen advies, geen hands-on",
                      "realAccelerate": "We zeggen waar het op staat"
                },
                {
                      "aspect": "Garantie",
                      "aspectIcon": "ShieldCheck",
                      "other": "Formele relaties",
                      "realAccelerate": "Plezier en ambitie gaan hand in hand"
                },
                {
                      "aspect": "Relatie",
                      "aspectIcon": "Handshake",
                      "other": "Snelle transacties",
                      "realAccelerate": "Duurzame relaties boven snelle deals"
                }
          ],
          "testimonial": {
                "quote": "Bij ons draait het niet alleen om strategieën en processen, maar vooral om mensen. We werken vanuit vertrouwen en gelijkwaardigheid, en we bouwen liever duurzame relaties dan snelle transacties.",
                "author": "Real Accelerate Team",
                "company": "Over onze aanpak"
          }
    },
  },
  'Over-ons-HeroSection': {
    name: 'Over-ons - Hero section',
    category: 'Over-ons',
    description: 'Over-ons - Hero section',
    defaultProps: {
          "badge": "Over ons",
          "title": "Van",
          "highlightedWord": "vastgoedondernemers",
          "subtitle": "voor vastgoedondernemers",
          "description": "Wij zijn Real Accelerate. Een team dat dagelijks actief is in de vastgoedbranche. We kennen de uitdagingen van binnenuit – omdat we ze zelf ervaren hebben. Vanuit die praktijk helpen we anderen vooruit met een aanpak die vernieuwend, praktisch en resultaatgericht is.",
          "image": "/images/teamfoto_einde.png",
          "imageAlt": "Team Real Accelerate",
          "stats": [
                {
                      "icon": "Users",
                      "value": "200+ klanten",
                      "label": "Europa-breed"
                },
                {
                      "icon": "Globe",
                      "value": "IQI Global Partner",
                      "label": "Internationale slagkracht"
                }
          ]
    },
  },
  'Over-ons-MissionSection': {
    name: 'Over-ons - Mission section',
    category: 'Over-ons',
    description: 'Over-ons - Mission section',
    defaultProps: {
          "badge": "Onze missie",
          "title": "Waarom Real Accelerate bestaat",
          "subtitle": "De vastgoedbranche vernieuwen en ondernemers helpen om sterker, efficiënter en toekomstbestendig te worden",
          "cards": [
                {
                      "icon": "Lightbulb",
                      "title": "Het probleem",
                      "content": "We zagen te vaak dat professionals in de vastgoedbranche <span class=\"font-semibold text-white\">vastliepen in dezelfde patronen:</span> <span class=\"text-[var(--brand-300)] font-medium\">gebrek aan structuur, afhankelijkheid van externe partijen en een moeizame weg naar groei.</span>"
                },
                {
                      "icon": "Rocket",
                      "title": "Onze oplossing",
                      "content": "Met onze eigen ondernemingen ontwikkelden we <span class=\"font-semibold text-[var(--brand-200)]\">strategieën en systemen die dit doorbraken.</span> <span class=\"text-white font-medium\">Het was een logische stap</span> om die kennis en ervaring te bundelen in Real Accelerate."
                },
                {
                      "icon": "Star",
                      "title": "Onze impact",
                      "content": "Ons doel is helder: <span class=\"font-semibold text-white\">de vastgoedbranche vernieuwen</span> en <span class=\"text-[var(--brand-200)] font-medium\">ondernemers helpen om sterker, efficiënter en toekomstbestendig te worden.</span>"
                }
          ],
          "tagline": "Van vastlooppatronen naar duurzame groei. Van afhankelijkheid naar zelfstandigheid. Van overleven naar floreren."
    },
  },
  'Over-ons-OfficeSection': {
    name: 'Over-ons - Office section',
    category: 'Over-ons',
    description: 'Over-ons - Office section',
    defaultProps: {
          "badge": "Office & Werkwijze",
          "title": "Waarom samenwerken met ons?",
          "subtitle": "🏢 Bezoek ons in Amsterdam",
          "latitude": 52.3239602,
          "longitude": 4.9586448,
          "address": {
                "street": "Daalwijkdreef 47",
                "city": "1103 AD Amsterdam"
          },
          "phone": "085 060 2989",
          "email": "info@realaccelerate.nl",
          "image": "/images/joep-koffie.png",
          "imageAlt": "Joep"
    },
  },
  'Over-ons-PartnershipsSection': {
    name: 'Over-ons - Partnerships section',
    category: 'Over-ons',
    description: 'Over-ons - Partnerships section',
    defaultProps: {
          "badge": "Partnerships",
          "title": "Onze Partnerships",
          "partnerships": [
                {
                      "title": "IQI Global",
                      "description": "Internationale expansie partner. Versterkt onze slagkracht met wereldwijde aanwezigheid en expertise.",
                      "image": "/images/iqiglobal.jpg",
                      "features": [
                            "Internationale expansie",
                            "40.000+ agents wereldwijd",
                            "Real Accelerate = IQI NL",
                            "Dubai, Spanje, Bali"
                      ]
                },
                {
                      "title": "SETTL.",
                      "description": "Ons eigen makelaarskantoor waar we dagelijks in de praktijk staan. Alles wat we doen voor onze klanten, hebben we zelf getest, verbeterd en bewezen.",
                      "image": "/images/editbv.jpg",
                      "features": [
                            "Eigen makelaarskantoor",
                            "Ervaring uit de praktijk",
                            "Bewezen strategieën",
                            "Real-world testing ground"
                      ]
                }
          ],
          "quote": "We spreken niet vanaf de zijlijn, maar met ondernemers die zelf midden in de vastgoedwereld staan en jouw doelen begrijpen.",
          "quoteAuthor": "Real Accelerate"
    },
  },
  'Over-ons-TeamSection': {
    name: 'Over-ons - Team section',
    category: 'Over-ons',
    description: 'Over-ons - Team section',
    defaultProps: {
          "badge": "Team",
          "title": "Het team achter Real Accelerate",
          "members": [
                {
                      "name": "Joep",
                      "role": "Founder — CEO",
                      "image": "/images/1.EmiroSmolders-Settle-DSC06894-.webp"
                },
                {
                      "name": "Partner Naam",
                      "role": "Co-Founder — CTO",
                      "image": "/images/2.EmiroSmolders-Settle-DSC06899-.webp"
                },
                {
                      "name": "Nina",
                      "role": "Klant succes baas",
                      "image": "/images/3.EmiroSmolders-Settle-DSC06907-.webp"
                },
                {
                      "name": "Ravi",
                      "role": "Sales tijger",
                      "image": "/images/4.EmiroSmolders-Settle-DSC06915-.webp"
                },
                {
                      "name": "Milo",
                      "role": "Creatieve baas",
                      "image": "/images/5.EmiroSmolders-Settle-DSC06927-.webp"
                },
                {
                      "name": "Sofie",
                      "role": "Data baas",
                      "image": "/images/6.EmiroSmolders-Settle-DSC06931-.webp"
                },
                {
                      "name": "Alex",
                      "role": "Product owner",
                      "image": "/images/10.EmiroSmolders-Settle-DSC06970-.webp"
                },
                {
                      "name": "Maya",
                      "role": "Design lead",
                      "image": "/images/9.EmiroSmolders-Settle-DSC06956-.webp"
                }
          ]
    },
  },
  'Over-ons-TimelineSection': {
    name: 'Over-ons - Timeline section',
    category: 'Over-ons',
    description: 'Over-ons - Timeline section',
  },
  'Over-ons-TrustStripSection': {
    name: 'Over-ons - Trust strip section',
    category: 'Over-ons',
    description: 'Over-ons - Trust strip section',
    defaultProps: {
          "items": [
                "Samen 30+ jaar marketing ervaring",
                "Gevestigd in Nederland",
                "Samen 40+ jaar vastgoed ervaring",
                "Persoonlijke benadering",
                "Transparante werkwijze",
                "Wereldwijd actief",
                "Data-driven beslissingen",
                "Innovatieve oplossingen",
                "Klantgericht team",
                "Bewezen track record"
          ]
    },
  },
  'Projectontwikkelaars-BewezenAanpakSection': {
    name: 'Projectontwikkelaars - Bewezen aanpak section',
    category: 'Projectontwikkelaars',
    description: 'Projectontwikkelaars - Bewezen aanpak section',
  },
  'Projectontwikkelaars-DubaiSuccessStorySection': {
    name: 'Projectontwikkelaars - Dubai success story section',
    category: 'Projectontwikkelaars',
    description: 'Projectontwikkelaars - Dubai success story section',
  },
  'Projectontwikkelaars-FAQSection': {
    name: 'Projectontwikkelaars - F a q section',
    category: 'Projectontwikkelaars',
    description: 'Projectontwikkelaars - F a q section',
  },
  'Projectontwikkelaars-Hero': {
    name: 'Projectontwikkelaars - Hero',
    category: 'Projectontwikkelaars',
    description: 'Projectontwikkelaars - Hero',
  },
  'Projectontwikkelaars-MethodologySection': {
    name: 'Projectontwikkelaars - Methodology section',
    category: 'Projectontwikkelaars',
    description: 'Projectontwikkelaars - Methodology section',
  },
  'Projectontwikkelaars-PainPointsSection': {
    name: 'Projectontwikkelaars - Pain points section',
    category: 'Projectontwikkelaars',
    description: 'Projectontwikkelaars - Pain points section',
  },
  'Projectontwikkelaars-ResultatenBentoGrid': {
    name: 'Projectontwikkelaars - Resultaten bento grid',
    category: 'Projectontwikkelaars',
    description: 'Projectontwikkelaars - Resultaten bento grid',
  },
  'Projectontwikkelaars-StrategieSessionCTA': {
    name: 'Projectontwikkelaars - Strategie session c t a',
    category: 'Projectontwikkelaars',
    description: 'Projectontwikkelaars - Strategie session c t a',
  },
  'Projectontwikkelaars-TrustStrip': {
    name: 'Projectontwikkelaars - Trust strip',
    category: 'Projectontwikkelaars',
    description: 'Projectontwikkelaars - Trust strip',
  },
  'Projectontwikkelaars-VoorWieIsDitSection': {
    name: 'Projectontwikkelaars - Voor wie is dit section',
    category: 'Projectontwikkelaars',
    description: 'Projectontwikkelaars - Voor wie is dit section',
  },
  'Projectontwikkelaars-WatJeKrijgtSection': {
    name: 'Projectontwikkelaars - Wat je krijgt section',
    category: 'Projectontwikkelaars',
    description: 'Projectontwikkelaars - Wat je krijgt section',
  },
  'Home-TestimonialsSection': {
    name: 'Home - Testimonials',
    category: 'Home',
    description: 'Customer testimonials with marquee',
    defaultProps: {
          "title": "Uitgelichte succesverhalen",
          "description": "MEER SUCCESVERHALEN",
          "durationSec": 70,
          "testimonials": [
                {
                      "title": "De Brabant Makelaar",
                      "imageSrc": "/images/brabantmakelaar_logo.webp",
                      "badges": [
                            "8 makelaars actief",
                            "Agenda gevuld"
                      ],
                      "author": {
                            "name": "Amory",
                            "handle": "De Brabant Makelaar",
                            "avatar": "/images/brabantmakelaar_avatar.webp"
                      },
                      "text": "De dynamische heren van Real Accelerate zijn erg fijn om mee samen te werken. Proactief en zorgen voor veel resultaten. Aanrader voor iedereen die meer uit online marketing wilt halen!",
                      "href": "/cases"
                },
                {
                      "title": "Bink & Partners",
                      "imageSrc": "/images/binkpartners_logo.webp",
                      "badges": [
                            "Leads boven verwachting",
                            "Website complimenten"
                      ],
                      "author": {
                            "name": "Pieter",
                            "handle": "Bink & Partners",
                            "avatar": "/images/binkpartners_avatar.webp"
                      },
                      "text": "Real Accelerate is een enthousiaste groep. Mijn nieuwe website levert veel complimenten op. Het vervolgtraject om op de socials leads te genereren is zojuist gestart en loopt prima.",
                      "href": "/cases"
                }
          ]
    },
  },
  'Home-TargetGroupsOverviewPhotos': {
    name: 'Home - Target groups photos',
    category: 'Home',
    description: 'Photo-based target group overview',
    defaultProps: {
          "title": "Voor wie wij werken",
          "subtitle": "Gespecialiseerde oplossingen voor elke vastgoedprofessional",
          "items": [
                {
                      "name": "Makelaars",
                      "description": "Duurzame klant‑relaties ipv lead‑jacht",
                      "img": "/images/remax.jpg",
                      "alt": "Re/max makelaars",
                      "href": "/makelaars",
                      "key": "makelaars"
                },
                {
                      "name": "Projectontwikkelaars",
                      "description": "Project marketing & events",
                      "img": "/images/recreatie.jpg",
                      "alt": "Recreatie projectontwikkeling",
                      "href": "/projectontwikkelaars",
                      "key": "projectontwikkelaars"
                },
                {
                      "name": "Hypotheekadviseurs",
                      "description": "Onafhankelijk van offerte‑sites worden",
                      "img": "/images/hypotheekvisie.jpg",
                      "alt": "Hypotheekvisie kantoor",
                      "href": "/hypotheekadviseurs",
                      "key": "hypotheek"
                },
                {
                      "name": "International",
                      "description": "IQI Global Partnership • Dubai, Spanje, Bali ervaring",
                      "img": "/images/secondhomebeurs.jpg",
                      "alt": "Second Home Beurs",
                      "href": "/makelaars-buitenland",
                      "key": "buitenland"
                }
          ]
    },
  },
}
