// Export all block types
export { HeroSection } from './HeroSection'
export { TrustStrip } from './TrustStrip'
export { ProblemSection } from './ProblemSection'
export { CaseStudy } from './CaseStudy'
export { UniqueApproach } from './UniqueApproach'
export { FlowConnector } from './FlowConnector'
export { MarketingMachine } from './MarketingMachine'
export { TargetGroupsOverview } from './TargetGroupsOverview'
export { TargetGroupsOverviewPhotos } from './TargetGroupsOverviewPhotos'
export { NumbersSection } from './NumbersSection'
export { TestimonialsSection } from './TestimonialsSection'
export { FAQSection } from './FAQSection'
export { HowItWorksSection } from './HowItWorksSection'
export { FinalCTA } from './FinalCTA'

// Cases blocks
export { CasesHero } from './CasesHero'
export { CasesBestVariants } from './CasesBestVariants'
export { CasesVideoTestimonials } from './CasesVideoTestimonials'
export { CasesMasonry } from './CasesMasonry'
export { CasesProjectsShowcase } from './CasesProjectsShowcase'
export { CasesIndustryBreakdown } from './CasesIndustryBreakdown'
export { CasesProcessShowcase } from './CasesProcessShowcase'
export { CasesStartYourStory } from './CasesStartYourStory'

// Over-ons blocks
export { OverOnsHeroSection } from './OverOnsHeroSection'
export { OverOnsTrustStripSection } from './OverOnsTrustStripSection'
export { OverOnsMissionSection } from './OverOnsMissionSection'
export { OverOnsTimelineSection } from './OverOnsTimelineSection'
export { OverOnsTeamSection } from './OverOnsTeamSection'
export { OverOnsCoreValuesSection } from './OverOnsCoreValuesSection'
export { OverOnsPartnershipsSection } from './OverOnsPartnershipsSection'
export { OverOnsCultureSection } from './OverOnsCultureSection'
export { OverOnsOfficeSection } from './OverOnsOfficeSection'
export { OverOnsCTASection } from './OverOnsCTASection'

// Makelaars blocks
export { MakelaarsHero } from './MakelaarsHero'
export { MakelaarsTrustStrip } from './MakelaarsTrustStrip'
export { MakelaarsProblemSection } from './MakelaarsProblemSection'
export { MakelaarsMethodologySection } from './MakelaarsMethodologySection'
export { MakelaarsBewezenSysteemSection } from './MakelaarsBewezenSysteemSection'
export { MakelaarsResultsBentoGrid } from './MakelaarsResultsBentoGrid'
export { MakelaarsGuaranteesSection } from './MakelaarsGuaranteesSection'
export { MakelaarsWhatYouGetSection } from './MakelaarsWhatYouGetSection'
export { MakelaarsForWhoIsThisSection } from './MakelaarsForWhoIsThisSection'
export { MakelaarsStrategieSessionCTA } from './MakelaarsStrategieSessionCTA'
export { MakelaarsFAQSection } from './MakelaarsFAQSection'
