/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * De URL van deze pagina (bijv. "makelaars" of "/" voor homepage)
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Sleep blokken om de volgorde te wijzigen. Klik op een blok om deze te bewerken.
   */
  blocks: (
    | {
        kicker?: string | null;
        title: string;
        subtitle?: string | null;
        ctaPrimary: {
          label: string;
          href: string;
        };
        ctaSecondary?: {
          label?: string | null;
          href?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroSection';
      }
    | {
        items: {
          text: string;
          id?: string | null;
        }[];
        ariaLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'trustStrip';
      }
    | {
        kicker?: string | null;
        title: string;
        subtitle?: string | null;
        oldSituation?: {
          title?: string | null;
          items?:
            | {
                icon: string;
                text: string;
                id?: string | null;
              }[]
            | null;
        };
        newSituation?: {
          title?: string | null;
          items?:
            | {
                icon: string;
                text: string;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'problemSection';
      }
    | {
        kicker?: string | null;
        title: string;
        subtitle?: string | null;
        tone?: ('light' | 'dark') | null;
        frameless?: boolean | null;
        showBackdropLogo?: boolean | null;
        image?: (number | null) | Media;
        /**
         * Beschrijving voor toegankelijkheid
         */
        imageAlt?: string | null;
        kpis?:
          | {
              label: string;
              from: number;
              to: number;
              unit?: ('eur' | 'percentage' | 'number') | null;
              sublabel?: string | null;
              span?: number | null;
              id?: string | null;
            }[]
          | null;
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        ctaPrimary?: {
          label?: string | null;
          href?: string | null;
        };
        ctaSecondary?: {
          label?: string | null;
          href?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'caseStudy';
      }
    | {
        kicker?: string | null;
        title: string;
        subtitle?: string | null;
        metricValue?: string | null;
        metricLabel?: string | null;
        card1Title?: string | null;
        card1Description?: string | null;
        card2Title?: string | null;
        card2Description?: string | null;
        card3Title?: string | null;
        card3Description?: string | null;
        card4Title?: string | null;
        card4Description?: string | null;
        ctaText?: string | null;
        ctaButtonLabel?: string | null;
        ctaButtonHref?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'uniqueApproach';
      }
    | {
        /**
         * Dit block heeft geen configureerbare opties - het is puur visueel
         */
        note?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'flowConnector';
      }
    | {
        title: string;
        subtitle?: string | null;
        features: {
          icon: string;
          name: string;
          description: string;
          href?: string | null;
          cta?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'marketingMachine';
      }
    | {
        title: string;
        subtitle?: string | null;
        items?:
          | {
              name: string;
              description: string;
              image?: (number | null) | Media;
              href?: string | null;
              key?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'targetGroupsOverview';
      }
    | {
        title: string;
        subtitle?: string | null;
        items: {
          name: string;
          description: string;
          image?: (number | null) | Media;
          /**
           * Beschrijving voor toegankelijkheid
           */
          alt?: string | null;
          href: string;
          /**
           * Unieke identifier voor deze doelgroep
           */
          key?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'targetGroupsOverviewPhotos';
      }
    | {
        title: string;
        stats: {
          value: string;
          label: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'numbersSection';
      }
    | {
        title: string;
        description?: string | null;
        durationSec?: number | null;
        testimonials: {
          title: string;
          companyLogo?: (number | null) | Media;
          badges?:
            | {
                text?: string | null;
                id?: string | null;
              }[]
            | null;
          author: {
            name: string;
            handle?: string | null;
            avatar?: (number | null) | Media;
          };
          text: string;
          href?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonialsSection';
      }
    | {
        title: string;
        subtitle?: string | null;
        items: {
          icon?: string | null;
          question: string;
          answer: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'faqSection';
      }
    | {
        title: string;
        subtitle?: string | null;
        steps: {
          title: string;
          subtitle?: string | null;
          icon: string;
          bullets?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'howItWorksSection';
      }
    | {
        title: string;
        subtitle?: string | null;
        ctaLabel: string;
        ctaHref: string;
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'finalCTA';
      }
    | CasesHero
    | CasesBestVariants
    | CasesVideoTestimonials
    | CasesMasonry
    | CasesProjectsShowcase
    | CasesIndustryBreakdown
    | CasesProcessShowcase
    | CasesStartYourStory
  )[];
  seo?: {
    /**
     * Verschijnt in Google zoekresulataten (max 60 karakters)
     */
    metaTitle?: string | null;
    /**
     * Verschijnt in Google zoekresulataten (max 160 karakters)
     */
    metaDescription?: string | null;
    /**
     * Afbeelding die getoond wordt bij delen op social media
     */
    ogImage?: (number | null) | Media;
  };
  organizationSchema?: {
    enabled?: boolean | null;
    name?: string | null;
    description?: string | null;
    contactEmail?: string | null;
    contactPhone?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesHero".
 */
export interface CasesHero {
  badge: string;
  title: string;
  titleHighlight: string;
  subtitle: string;
  ctaPrimary: string;
  ctaSecondary: string;
  ctaSecondaryHref: string;
  stats?:
    | {
        icon?: string | null;
        label?: string | null;
        value?: number | null;
        suffix?: string | null;
        id?: string | null;
      }[]
    | null;
  image: string;
  imageAlt: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'casesHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesBestVariants".
 */
export interface CasesBestVariants {
  badge: string;
  title: string;
  subtitle: string;
  featuredBadge: string;
  featuredCompany: string;
  featuredSubtitle: string;
  featuredImage: string;
  featuredImageAlt: string;
  stats?:
    | {
        icon?: string | null;
        label?: string | null;
        from?: string | null;
        to?: string | null;
        suffix?: string | null;
        id?: string | null;
      }[]
    | null;
  results?:
    | {
        icon?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  otherCases?:
    | {
        company?: string | null;
        sector?: string | null;
        icon?: string | null;
        highlight?: string | null;
        bullets?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        image?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'casesBestVariants';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesVideoTestimonials".
 */
export interface CasesVideoTestimonials {
  badge: string;
  title: string;
  subtitle: string;
  durationBadge: string;
  activeIndicator: string;
  sidebarHeader: string;
  videos?:
    | {
        id?: number | null;
        company?: string | null;
        name?: string | null;
        role?: string | null;
        thumbnail?: string | null;
        videoUrl?: string | null;
        quote?: string | null;
        highlight?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'casesVideoTestimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesMasonry".
 */
export interface CasesMasonry {
  kicker: string;
  title: string;
  subtitle: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'casesMasonry';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesProjectsShowcase".
 */
export interface CasesProjectsShowcase {
  badge: string;
  title: string;
  subtitle: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'casesProjectsShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesIndustryBreakdown".
 */
export interface CasesIndustryBreakdown {
  id?: string | null;
  blockName?: string | null;
  blockType: 'casesIndustryBreakdown';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesProcessShowcase".
 */
export interface CasesProcessShowcase {
  badge: string;
  title: string;
  subtitle: string;
  steps?:
    | {
        number?: string | null;
        title?: string | null;
        subtitle?: string | null;
        icon?: string | null;
        items?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        timeline?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'casesProcessShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesStartYourStory".
 */
export interface CasesStartYourStory {
  badge: string;
  title: string;
  titleHighlight: string;
  benefits?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel: string;
  ctaSubtext: string;
  ctaFootnote: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'casesStartYourStory';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  blocks?:
    | T
    | {
        heroSection?:
          | T
          | {
              kicker?: T;
              title?: T;
              subtitle?: T;
              ctaPrimary?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              ctaSecondary?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        trustStrip?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              ariaLabel?: T;
              id?: T;
              blockName?: T;
            };
        problemSection?:
          | T
          | {
              kicker?: T;
              title?: T;
              subtitle?: T;
              oldSituation?:
                | T
                | {
                    title?: T;
                    items?:
                      | T
                      | {
                          icon?: T;
                          text?: T;
                          id?: T;
                        };
                  };
              newSituation?:
                | T
                | {
                    title?: T;
                    items?:
                      | T
                      | {
                          icon?: T;
                          text?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        caseStudy?:
          | T
          | {
              kicker?: T;
              title?: T;
              subtitle?: T;
              tone?: T;
              frameless?: T;
              showBackdropLogo?: T;
              image?: T;
              imageAlt?: T;
              kpis?:
                | T
                | {
                    label?: T;
                    from?: T;
                    to?: T;
                    unit?: T;
                    sublabel?: T;
                    span?: T;
                    id?: T;
                  };
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              ctaPrimary?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              ctaSecondary?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        uniqueApproach?:
          | T
          | {
              kicker?: T;
              title?: T;
              subtitle?: T;
              metricValue?: T;
              metricLabel?: T;
              card1Title?: T;
              card1Description?: T;
              card2Title?: T;
              card2Description?: T;
              card3Title?: T;
              card3Description?: T;
              card4Title?: T;
              card4Description?: T;
              ctaText?: T;
              ctaButtonLabel?: T;
              ctaButtonHref?: T;
              id?: T;
              blockName?: T;
            };
        flowConnector?:
          | T
          | {
              note?: T;
              id?: T;
              blockName?: T;
            };
        marketingMachine?:
          | T
          | {
              title?: T;
              subtitle?: T;
              features?:
                | T
                | {
                    icon?: T;
                    name?: T;
                    description?: T;
                    href?: T;
                    cta?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        targetGroupsOverview?:
          | T
          | {
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    name?: T;
                    description?: T;
                    image?: T;
                    href?: T;
                    key?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        targetGroupsOverviewPhotos?:
          | T
          | {
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    name?: T;
                    description?: T;
                    image?: T;
                    alt?: T;
                    href?: T;
                    key?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        numbersSection?:
          | T
          | {
              title?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonialsSection?:
          | T
          | {
              title?: T;
              description?: T;
              durationSec?: T;
              testimonials?:
                | T
                | {
                    title?: T;
                    companyLogo?: T;
                    badges?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    author?:
                      | T
                      | {
                          name?: T;
                          handle?: T;
                          avatar?: T;
                        };
                    text?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqSection?:
          | T
          | {
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    icon?: T;
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        howItWorksSection?:
          | T
          | {
              title?: T;
              subtitle?: T;
              steps?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    icon?: T;
                    bullets?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        finalCTA?:
          | T
          | {
              title?: T;
              subtitle?: T;
              ctaLabel?: T;
              ctaHref?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        casesHero?: T | CasesHeroSelect<T>;
        casesBestVariants?: T | CasesBestVariantsSelect<T>;
        casesVideoTestimonials?: T | CasesVideoTestimonialsSelect<T>;
        casesMasonry?: T | CasesMasonrySelect<T>;
        casesProjectsShowcase?: T | CasesProjectsShowcaseSelect<T>;
        casesIndustryBreakdown?: T | CasesIndustryBreakdownSelect<T>;
        casesProcessShowcase?: T | CasesProcessShowcaseSelect<T>;
        casesStartYourStory?: T | CasesStartYourStorySelect<T>;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  organizationSchema?:
    | T
    | {
        enabled?: T;
        name?: T;
        description?: T;
        contactEmail?: T;
        contactPhone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesHero_select".
 */
export interface CasesHeroSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  titleHighlight?: T;
  subtitle?: T;
  ctaPrimary?: T;
  ctaSecondary?: T;
  ctaSecondaryHref?: T;
  stats?:
    | T
    | {
        icon?: T;
        label?: T;
        value?: T;
        suffix?: T;
        id?: T;
      };
  image?: T;
  imageAlt?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesBestVariants_select".
 */
export interface CasesBestVariantsSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  subtitle?: T;
  featuredBadge?: T;
  featuredCompany?: T;
  featuredSubtitle?: T;
  featuredImage?: T;
  featuredImageAlt?: T;
  stats?:
    | T
    | {
        icon?: T;
        label?: T;
        from?: T;
        to?: T;
        suffix?: T;
        id?: T;
      };
  results?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  otherCases?:
    | T
    | {
        company?: T;
        sector?: T;
        icon?: T;
        highlight?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesVideoTestimonials_select".
 */
export interface CasesVideoTestimonialsSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  subtitle?: T;
  durationBadge?: T;
  activeIndicator?: T;
  sidebarHeader?: T;
  videos?:
    | T
    | {
        id?: T;
        company?: T;
        name?: T;
        role?: T;
        thumbnail?: T;
        videoUrl?: T;
        quote?: T;
        highlight?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesMasonry_select".
 */
export interface CasesMasonrySelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  subtitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesProjectsShowcase_select".
 */
export interface CasesProjectsShowcaseSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  subtitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesIndustryBreakdown_select".
 */
export interface CasesIndustryBreakdownSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesProcessShowcase_select".
 */
export interface CasesProcessShowcaseSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  subtitle?: T;
  steps?:
    | T
    | {
        number?: T;
        title?: T;
        subtitle?: T;
        icon?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        timeline?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesStartYourStory_select".
 */
export interface CasesStartYourStorySelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  titleHighlight?: T;
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaSubtext?: T;
  ctaFootnote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}